### ISSUE TITLE
Raspbian Bullseye: ImportError: _miniaudio.abi3.so: undefined symbol: __atomic_load_8

### ISSUE THREAD

**Issue by phiwop** [postlund/pyatv#1765] opened 2022-06-26 09:43 UTC
### What do you need help with?

Hey,

trying to install pyatv via "pip3 install --upgrade git+https://github.com/postlund/pyatv.git" and "pip3 install pyatv". All Dependencies are fulfilled. But there seems to be a Problem with miniaudio.

Error:
Traceback (most recent call last):
  File "/home/julian/airplaybluepi/main.py", line 6, in <module>
    import pyatv
  File "/home/julian/airplaybluepi/pyatv/__init__.py", line 18, in <module>
    from pyatv.core.scan import (
  File "/home/julian/airplaybluepi/pyatv/core/scan.py", line 32, in <module>
    from pyatv.helpers import get_unique_id
  File "/home/julian/airplaybluepi/pyatv/helpers.py", line 6, in <module>
    import miniaudio
  File "/home/julian/.local/lib/python3.9/site-packages/miniaudio.py", line 22, in <module>
    from _miniaudio import ffi, lib
ImportError: /home/julian/.local/lib/python3.9/site-packages/_miniaudio.abi3.so: undefined symbol: __atomic_load_8

Any Ideas how to solve this ? Down/Upgrade Miniaudio ? 

Best regards, 
Julian

**Comment by postlund** [comment] 2022-06-26 10:04
Duplicate of #1762.

**Comment by phiwop** [comment] 2022-06-26 10:17
Thank you for the hint. Didn't saw it.

**Closed** 2022-06-26 16:34 UTC
Labels: duplicate, question
