### ISSUE TITLE
Playback/Audio Source Questions

### ISSUE THREAD

**Issue by 400HPMustang** [postlund/pyatv#1451] opened 2021-11-05 21:43 UTC
### What's on your mind?

I just installed the HASS ATV Beta today and if I select a HomePod and hit play on a media player card then music starts...is this just shuffling/randomly playing stuff from my iTunes library?

Is there a way to get a HomePod to play something from Apple Music? or can I stream an MP3 stream to it the same way I can do with my Sonos?

**Comment by postlund** [comment] 2021-12-02 12:48
Sorry, I must have missed this issue completely! If you press play, the HomePod will play whatever it thinks it played last (from your Music). I don't know how playing anything from Apple Music works (but would love to support that). You can stream audio files (WAV, MP3, OGG and FLAC using `stream_file` (it is used automatically if you pass a local filename to the `play_media` service in Home Assistant). It is not supported to stream non-local files, like via HTTP(s).

**Comment by 400HPMustang** [comment] 2021-12-03 14:54
Ah ok. I was hoping to be able to do something like play a stream from https like this

https://playerservices.streamtheworld.com/api/livestream-redirect/WKQXFM.mp3

Since I can send that to my Sonos, it would be nice if my HomePods could play that stream too. 

As far as Apple Music, this is a thing but it doesn't seem like anyone is integrating it with anything or even looking at how to do it https://developer.apple.com/musickit/

**Comment by postlund** [comment] 2021-12-03 14:59
I was actually working on supporting that earlier today. I might be able to push something you can try later tonight.

**Comment by 400HPMustang** [comment] 2021-12-03 15:00
Oh heck yeah. Thank you!

**Comment by postlund** [comment] 2021-12-03 21:33
Please try #1490 and let me know if it works! It's still early stuff so might be a bit unstable, but hopefully it's better than what we have.

**Comment by 400HPMustang** [comment] 2021-12-03 21:40
This may be a dumb question but what's the easiest way to get this branch working in Home Assistant to test out?

**Comment by postlund** [comment] 2021-12-03 21:44
Getting it to work in Home Assistant is tedious without a release to pypi (so you can change version in the manifest file). I suggest try it using `atvremote -s <HomePod IP> stream_file=<url>`. Some install instructions are here:

https://pyatv.dev/documentation/#installing-pyatv

There's a specific section for installing from a PR there as well.

**Comment by postlund** [comment] 2021-12-06 09:36
I just pushed an update to the beta component, so you can just upgrade in HACS and try it out from there. Please give it a go and let me know if it works!

**Comment by 400HPMustang** [comment] 2021-12-06 11:47
I just downloaded it and restarted HA and it shows my devices as not loaded and the following errors in the logs

```
Logger: homeassistant
Source: custom_components/apple_tv/config_flow.py:149
Integration: Apple TV
First occurred: 5:43:51 AM (3 occurrences)
Last logged: 5:44:59 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 170, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/config_flow.py", line 59, in <module>
    class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/config/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
    self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'
```


```
Logger: homeassistant.bootstrap
Source: custom_components/apple_tv/config_flow.py:149
Integration: Apple TV
First occurred: 5:43:50 AM (1 occurrences)
Last logged: 5:43:50 AM

Error setting up integration apple_tv - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 104, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 287, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 283, in async_setup
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/config_flow.py", line 59, in <module>
    class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/config/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
    self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'

```

**Comment by postlund** [comment] 2021-12-06 11:55
I was made aware of that a bit late 😞 Made some code uplifts from core and those changes, yet again, will be available in the next release. So you either have to run beta or wait until the upcoming weekend for the next release. Sorry about that!

**Comment by 400HPMustang** [comment] 2021-12-06 11:56
I can run a beta version, that's fine. It just doesn't show me a beta version available.

**Comment by postlund** [comment] 2021-12-06 11:59
You will have to "Join beta" channel in the supervisor I think.

**Comment by 400HPMustang** [comment] 2021-12-06 12:29
Ok so I got the home assistant beta installed and updated to latest Apple TV beta plugin. Streaming from a URL works fine, maybe a few seconds delay when it starts but that's not a big problem. I think one thing maybe just to note is the HomePods don't respond to the pause command so media players need to be configured with a stop button instead?

**Comment by postlund** [comment] 2021-12-06 13:10
Yeah, AirPlay has a built-in latency. Apple normally uses 2s for AirPlay 1 and 2,25s for AirPlay 2 (I arbitrarily use 1,5s in pyatv). There's also some buffering and propagation latency which I haven't made any attempts to measure.

Right, hmm, yeah. The problem is that the "feature set" reported by Home Assistant will be the union of what MRP and RAOP supports, even though RAOP (which performs the streaming) only supports `stream_file` and `stop`. So the UI will show the pause button instead of a stop button. A temporary work-around is to change so that pause triggers a "stop" when streaming something. It is possible to call `media_stop` service to force stopping playback for now. Would have preferred the frontend to always show pause and stop when something is playing.

**Comment by postlund** [comment] 2021-12-07 12:16
I have opened #1507 which makes the pause button stop playback. It's somewhat a hack but I think it's better for now.

**Comment by postlund** [comment] 2021-12-13 07:32
#1507 is merged so pause will stop in the next release.

**Closed by postlund** 2021-12-13 07:32 UTC
Labels: question, 3rd party, confirmation
