### ISSUE TITLE
play_url not working

### ISSUE THREAD

**Issue by HennieLP** [postlund/pyatv#2064] opened 2023-06-19 20:11 UTC
### Describe the bug

if i try ```atv.stream.play_url("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4")```
the apple tv goes plack and shows an Loading symbol but after 4 second it goes back to the home screen

### How to reproduce the bug?

use  ```atv.stream.play_url("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4")```

### What is expected behavior?

it plays the video on the apple tv

### Operating System

windows

### Python

Other

### pyatv

0.13.0

### Device

Apple TV 4K (gen2) TVos 16.3.1

### Additional context

-

**Comment by postlund** [comment] 2023-06-28 13:02
This is a known open issue that I more or less given up on. After some digging and trial an error though, I have managed to restore most of the functionality via AirPlay 2 (supporting newer devices). My main issue right know is that the video starts in paused state and I can't seem to figure out how to fix that. Will have to continue testing. There's a lot of cleanup to do as well, so I don't expect to have a fix for this for a while. Probably after summer or something like that.

**Comment by postlund** [comment] 2023-06-28 18:13
I figured out how to get playback to start automatically, so I think I can fix this.

**Comment by postlund** [comment] 2023-06-29 12:19
Ah, it's probably because I'm not sending any response on the event channel.

**Comment by postlund** [comment] 2023-06-29 12:26
Well yep, seems like that was it. Rookie mistake that I have made before...

**Comment by postlund** [comment] 2023-06-30 12:23
@HennieLP Just pushed #2079 which should fix this, can you verify this?

**Comment by postlund** [comment] 2023-06-30 12:52
It is currently not possible to stop the playback but I will fix that before merging the PR.

**Comment by oxplot** [comment] 2023-07-01 02:27
@postlund I can confirm that not *only* does it work, but it works better than before. Specifically, running `atremote play_url=` no longer requires the TV to be on to work properly. It turns on the TV and starts playing automatically.

In other words, tremendous success and I'm very happy.

**Comment by postlund** [comment] 2023-07-01 09:42
@oxplot That's great! 👍 I'm gonna try to fix `stop` and then I'll merge it.

**Comment by seidtgeist** [comment] 2023-07-03 18:31
@postlund Absolute legend! I had "Require password" enabled on my Apple TV 4K Gen1 which tripped up the RTSP authentication, but once it's disabled everything is working perfectly. Thank you!

**Comment by postlund** [comment] 2023-07-03 20:05
@seidtgeist 😎 Yeah, password is not supported for AirPlay yet but should probably be fixed at some point. It's already implemented for RAOP, so it should be fairly easy to just port that over.

**Comment by postlund** [comment] 2023-07-30 09:54
This is merged and will be part of the next release.

**Closed by postlund** 2023-07-30 09:54 UTC
Labels: bug
