### ISSUE TITLE
Apple TV 4 still not found?!

### ISSUE THREAD

**Issue by jayfbeast** [postlund/pyatv#312] opened 2019-12-08 21:10 UTC
Good day!

Even though it seems like many, many people successfully paired their ATV4 with your beta component, I'm still getting a "Apple TV not found" error when trying to add it to HA.

I've manually installed the beta custom component to HA and still no luck. 

I'm running HA 102.3 on Docker, which is running on Ubuntu 18.04 on an Intel NUC. 

I've accessed /bin/bash inside my Docker Container and manually executed `atvremote scan` and I still have empty results. 

Thank you!

**Comment by postlund** [comment] 2019-12-09 05:49
I was waiting for this report... 😊 At this point I'm not really sure what to do. If you scan a few times *outside* of the docker container, are you able to find it at all? Do you know if zeroconf works on other devices, e.g. does your Apple TV shoe up on your phone?

**Comment by postlund** [comment] 2019-12-11 07:11
I'm gonna leave this issue be for now, but treat it as a duplicate of #292.

**Comment by jayfbeast** [comment] 2019-12-11 12:35
Right after work I’ll start some investigation in my side as well and provide the best possible information for you. One thing though... do you want me to post those info on #292?

Sent from my iPhone.
On Dec 11, 2019, 2:11 AM -0500, Pierre Ståhl <notifications@github.com>, wrote:

I'm gonna leave this issue be for now, but treat it as a duplicate of #292<https://github.com/postlund/pyatv/issues/292>.

**Comment by postlund** [comment] 2019-12-11 12:53
Yeah, lets continue it in #292 so we keep everything we know in the same place. It will also trigger notifications for other people involved in the discussions so that we can help each other.

**Comment by postlund** [comment] 2020-01-23 11:45
I just closed #292, so I'm closing this as well now.

**Closed by postlund** 2020-01-23 11:45 UTC
Labels: 3rd party, question
