### ISSUE TITLE
Support launchable app names

### ISSUE THREAD

**Issue by rodhall** [postlund/pyatv#1442] opened 2021-11-01 19:35 UTC
### What feature would you like?

The new version of tvOS appears to have launchable app names that allow for direct launching of specific apps. This would be great to look at supporting.

### Describe the solution you'd like

Ability to feed launchable app names into the system for execution via Home Assistant.

### Any other information to share?

Name examples:

    "com.8player" = "8player Pro";
    "com.amazon.aiv.AIVApp" = "Prime Video";
    "com.amctve.amcfullepisodes" = AMC;
    "com.apple.Arcade" = Arcade;
    "com.apple.Fitness" = Fitness;
    "com.apple.TVAppStore" = "App Store";
    "com.apple.TVBooks" = "iBooks StoryTime";
    "com.apple.TVHomeSharing" = Computers;
    "com.apple.TVMovies" = Movies;
    "com.apple.TVMusic" = Music;
    "com.apple.TVPhotos" = Photos;
    "com.apple.TVSearch" = Search;
    "com.apple.TVSettings" = Settings;

**Comment by postlund** [comment] 2021-11-01 21:23
Yeah, it will be supported when support for app launching is added. Will close as duplicate of #832.

**Closed by postlund** 2021-11-01 21:23 UTC
Labels: feature
