### ISSUE TITLE
After update 2.0.0. - Config flow could not be loaded

### ISSUE THREAD

**Issue by JuhaFIN1** [postlund/pyatv#1503] opened 2021-12-06 13:26 UTC
### Describe the bug

Cannot add new device under Integations - Apple Tv anymore and already config device dont work either anymore.
I removed every apple device - reboot: no help, same error.

I unistalled new 2.0.0 and installer last version 1.9.1. - same error now: Config flow could not be loaded

Debug is on in yaml, dont just know how to share this dat
<img width="289" alt="Screenshot 2021-12-06 145152" src="https://user-images.githubusercontent.com/70380474/144853690-e6eb3f35-1655-4ab4-9346-0e9f98b62d46.png">
a?

### Error log

```log
<place log here>
```

### How to reproduce the bug?

just try to use it.

### What is expected behavior?

dont work

### Operating System

Windows 11 / VM Box

### Python

Other

### pyatv

?

### Device

Apple tv 4k + Apple tv 4k + Apple homepod mini x 2

### Additional context

...

**Comment by postlund** [comment] 2021-12-06 13:28
Duplicate of #1501

**Closed by postlund** 2021-12-06 13:28 UTC
Labels: bug

**Comment by JuhaFIN1** [comment] 2021-12-06 13:29
Please, this is not same as #1501, because rollback DIDNT help !

**Comment by JuhaFIN1** [comment] 2021-12-06 13:30
Logger: aiohttp.server
Source: custom_components/apple_tv/config_flow.py:149
Integration: apple_tv
First occurred: 15:20:26 (1 occurrences)
Last logged: 15:20:26

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/config_flow.py", line 59, in <module>
    class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/config/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
    self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'

**Comment by postlund** [comment] 2021-12-06 13:32
Yes, it is the same problem but the rollback didn't work for you. Did you restart Home Assistant afterwards?

**Comment by JuhaFIN1** [comment] 2021-12-06 13:35
Of course, hacks tell to do it every time you do some install / update. 
Now i have restarted 3 times: Same problem

**Comment by postlund** [comment] 2021-12-06 13:40
Then it's some kind of caching issue with HACS or something because the source code of 1.9.1 does not look like that as you can see here:

https://github.com/postlund/hass-atv-beta/blob/cd2072c00189a56d5d423b1b1b4baaea278ce2e9/custom_components/apple_tv/config_flow.py#L149

Try removing it completely from HACS, double check that it has been removed in your custom_components directory, restart HA and install again.

**Comment by JuhaFIN1** [comment] 2021-12-06 13:52
Yeah! that helped me get back 1.9.1. ( double restart ) So is there maybe change 2.0.0 would work too same way?

**Comment by postlund** [comment] 2021-12-06 13:58
You could revert changes until you get it working, but I would suggest joining the beta channel in that case.

**Comment by JuhaFIN1** [comment] 2021-12-06 14:00
Yeah i would like to join beta, just tell me how to do it :)

**Comment by postlund** [comment] 2021-12-06 14:01
I think you can enable it from the supervisor menu and then update Home Assistant after that.

**Comment by JuhaFIN1** [comment] 2021-12-06 14:09
Done! After i removed atv beta 1.9.1 hacks and reboot -> install atv beta 2.0.0 -> reboot. And now working! Thank you!

**Comment by postlund** [comment] 2021-12-06 15:14
Awesome! 👍
