### ISSUE TITLE
What is recommended for best performance

### ISSUE THREAD

**Issue by porgland** [postlund/pyatv#682] opened 2020-06-03 02:36 UTC
Hi ,
 First of all thank you for the amazing work on this . I am just wondering what hardware is recommended for best performance  ?  I am currently using a vero4k ARM based box to fire off commands to an ATV 4K MRP and there is a 3 sec delay between commands executing , I have also tried with laptop I7 based and it is better but still about 1.5 second delay ...so just wondering if there is a piece of hardware that performs best - Just for Reference I have an RTI control system which has an Apple TV MRP driver and the speed instantaneous , it is not as well featured as PYATV but interesting doesn't  require any remote paring .

**Comment by postlund** [comment] 2020-06-03 04:29
Once the connection to your device is set up, it's more or less instantaneous no matter what hardware you use. Since it's python and it has a few dependencies, it will of course take some time to load it up at first but on decent hardware that is not really a problem.

I assume you are using `atvremote`? Every time you run `atvremote` it will do a scan to find your device (with zeroconf) and a timeout of three seconds is used for that (and you will *always* get a penalty of that time, unless you change the length). Once the device is found a connection must be set up, encryption enabled and so on. That of course takes some time, but it's quite fast even on modest hardware. Since `atvremote` disconnects and and exits after every command, you will have to do scanning and connection set up again every time. That I why it feels like it has low performance, even though it hasn't.

The problem is that you cannot use `atvremote` and assume instantaneous feedback because that is not what that script is designed for. You need something that establish a connection to the device, maintains that and is put to run in the background. Using the Home Assistant integration will give you that for instance. I have a plan to include some sort of REST-like bridge in `atvscript` in the future, but I haven't come around to add support for that. `pytav` is first and foremost a library to build software that can talk to Apple TV's and `atvremote` is just a reference application that shows what you can do.

You don't really need to do pairing with `pyatv` either, it works without that. But I still recommend it since Apple might decide to change that at some point.

At the end, I can just mention unicast scanning. Using that, the scanning process will talk directly to one device. This is much faster (but of course, will still give you some penalty). You can use that as a middle ground, as long as you are on the same subnet as your Apple TV:

```
$ atvremote -s 10.0.0.4 playing
```

Some references:
https://pyatv.dev/documentation/atvremote/#discovering-specific-devices
https://pyatv.dev/documentation/concepts/#scanning

**Comment by porgland** [comment] 2020-06-03 04:43
Ok thank you ,  that makes sense now , again thank you for your work on this .

**Comment by postlund** [comment] 2020-06-03 04:49
Thank you and no worries 😊 Let me know if you need any additional help!

**Comment by postlund** [comment] 2020-06-04 09:05
I guess we can close this.

**Closed by postlund** 2020-06-04 09:05 UTC
Labels: question
