### ISSUE TITLE
Can find device with scanning but can't connect or send commands

### ISSUE THREAD

**Issue by parautenbach** [postlund/pyatv#1394] opened 2021-10-13 20:00 UTC
### Describe the bug

I've noticed that I'm unable to send commands to my Apple TV using the Home Assistant integration's remote. I then used the `atvremote` utility directly from the HA venv, which resulted in the same error.

### Error log

This is from my HA log, but I get exactly the same when sending e.g. the `home` command with `atvremote`
```log
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/apple_tv/__init__.py", line 225, in _connect_loop
    await self._connect(conf)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/apple_tv/__init__.py", line 309, in _connect
    self.atv = await connect(conf, self.hass.loop, session=session)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/__init__.py", line 127, in connect
    await atv.connect()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/support/facade.py", line 412, in connect
    await protocol_connect()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/__init__.py", line 743, in _connect
    await protocol.start()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 129, in start
    self.device_info = await self.send_and_receive(msg)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 216, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 224, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

I also tried to issue a pair command (with `atvremote`) which resulted in:
```log
2021-10-13 21:50:03 ERROR [root]: Pairing failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 489, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/auth.py", line 39, in start_pairing
    await self.protocol.start(skip_initial_messages=True)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 129, in start
    self.device_info = await self.send_and_receive(msg)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 216, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/protocol.py", line 224, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 177, in pair
    await self._perform_pairing(pairing)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 187, in _perform_pairing
    await pairing.begin()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/mrp/pairing.py", line 50, in begin
    return await error_handler(
  File "/srv/homeassistant/lib/python3.9/site-packages/pyatv/support/__init__.py", line 35, in error_handler
    raise exceptions.ConnectionFailedError(str(ex)) from ex
pyatv.exceptions.ConnectionFailedError
```

### How to reproduce the bug?

I'm using the pyatv 0.8.2 which is bundled with HA 2021.9.7. 

### What is expected behavior?

Being able to send commands like before.

### Operating System

Debian

### Python

3.9

### pyatv

0.8.2

### Device

Gen4 tvOS 15.0 build 19J346

### Additional context

Scanning works fine, so I'm pretty sure it's not a networking issue. 

```
       Name: Living Room
   Model/SW: Gen4 tvOS 15.0 build 19J346
    Address: xxx
        MAC: xxx
 Deep Sleep: True
Identifiers:
 - xxx
 - xxx
 - xxx
Services:
 - Protocol: Companion, Port: 49153, Credentials: None
 - Protocol: AirPlay, Port: 7000, Credentials: None
 - Protocol: MRP, Port: 49152, Credentials: None
 - Protocol: RAOP, Port: 7000, Credentials: None
```

**Comment by parautenbach** [comment] 2021-10-13 20:02
I've checked the HA release notes for 2021.9 and 2021.10 (that I still need to upgrade to) and the latest pyatv releases (0.8.2 onwards) for clues, but couldn't find anything that seems relevant to me.

**Comment by postlund** [comment] 2021-10-13 20:08
No, that will not work. You need to run the beta component to get it going again (until the changes are merged back to HA):

https://github.com/postlund/hass-atv-beta

Duplicate of #51649

**Closed** 2021-10-17 10:27 UTC
Labels: bug, duplicate, 3rd party
