### ISSUE TITLE
Apple TV: Not timing out when something is paused

### ISSUE THREAD

**Issue by RefineryX** [postlund/pyatv#908] opened 2020-12-29 13:12 UTC
I sometimes turn off my Apple TV while watching a TV show _(or it turns off automatically)_. After which, the card within Home Assistant continues to display the show in a playing or paused state and does not time out.
<img width="336" alt="Screenshot 2020-12-29 at 12 19 56" src="https://user-images.githubusercontent.com/46373533/103285392-f14ab980-49d5-11eb-90d4-dbdc982a1959.png">

<img width="911" alt="Screenshot 2020-12-29 at 12 20 36" src="https://user-images.githubusercontent.com/46373533/103285411-fc054e80-49d5-11eb-884e-c917a1583a95.png">

**To Reproduce**
1. While watching a show, press and hold the home until the menu displays on the right hand side of the screen
2. select 'sleep'
The show will continue to display in Home Assistant in a paused state. It has been in the paused state for 48+ hours.

**Expected behavior**
I would have expected it would recognise that the Apple TV is powered down into sleep mode and then put the status to idle or that the ATV has been paused for x period then timeout?

**System Setup (please complete the following information):**
 - OS: Raspberry Pi OS
 - Python: 2.7.16
 - pyatv: Integration within HA 2020.12.1
- Apple TV: Apple TV iOS 14.3 (18K561)

**Comment by postlund** [comment] 2020-12-29 13:28
This is because of #905, I'm currently working on that.

**Comment by RefineryX** [comment] 2020-12-29 23:28
Brilliant! Thank you very much.

**Comment by postlund** [comment] 2021-02-16 21:43
Can you please re-test with latest Home Assistant?

**Comment by postlund** [comment] 2021-02-26 21:41
@RefineryX Can you re-test with latest version of Home Assistant?

**Comment by postlund** [comment] 2021-04-21 12:56
Last bump before closing issue, does problem still exist?

**Comment by RefineryX** [comment] 2021-04-21 12:58
Thanks for the lodge @postlund .

Yes, the problem still exists on both my Apple TVs. All running the latest version of TVos and Home Assistant.

**Comment by postlund** [comment] 2021-04-21 17:00
No worries! Sounds like something I must have missed then. Is it easy to reproduce? Would be great to get a log, preferably if it can be reproduced with `atvremote ... push_updates`?

**Comment by postlund** [comment] 2021-04-28 12:01
Ping

**Comment by RefineryX** [comment] 2021-04-29 13:48
Hi there.

Sure, happy to provide anything you need. Would you mind guiding me through on how to contain the log through the ``atvremote ... push_updates`` and I will get that over to you.

**Comment by postlund** [comment] 2021-06-16 12:09
@RefineryX Sorry about the delay... First you need to install pyatv on a computer on the same network as your Apple TV. Instructions [here](https://pyatv.dev/documentation/#installing-pyatv). Then you just run `atvremote -s <apple tv ip> --debug push_updates` while triggering the bug. The output is what I'm interested in.

**Closed** 2021-10-18 12:33 UTC
Labels: bug, confirmation
