### ISSUE TITLE
Send Siri command via atvscript  

### ISSUE THREAD

**Issue by sklever** [postlund/pyatv#1818] opened 2022-08-04 20:51 UTC
Is it possible to send Siri commands to an Apple TV via atvscript? 
Would be great as then you can use this to switch TV channels for instance.
Apple TV’ Siri is also available on iOS when remote is displayed

**Comment by postlund** [comment] 2022-08-04 20:59
Nope, Siri support is not implemented yet (but I might give it a go at some point as I find it rather interesting). Duplicate of #170.

**Closed by postlund** 2022-08-04 20:59 UTC
Labels: question
