### ISSUE TITLE
Error handling request

### ISSUE THREAD

**Issue by fedebruni84** [postlund/pyatv#626] opened 2020-04-28 15:30 UTC
**Describe the bug**

Can’t set up the integration  

**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: Home Assistant Supervised on Ubuntu Server 
 - Python: 3.7.7
 - pyatv: latest
- Apple TV: Apple TV 4K tvOS 13.4

**Additional context**

```txt

Logger: aiohttp.server
Source: custom_components/apple_tv/__init__.py:8 
First occurred: 5:16:29 PM (3 occurrences) 
Last logged: 5:16:36 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 62, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 100, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/__init__.py", line 8, in <module>
    from pyatv import connect, exceptions, scan
  File "/usr/local/lib/python3.7/site-packages/pyatv/__init__.py", line 20, in <module>
    from pyatv.mrp import MrpAppleTV
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/__init__.py", line 25, in <module>
    from pyatv.mrp import messages, protobuf
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/messages.py", line 140, in <module>
    identifier, send_error=protobuf.SendCommandResultMessage.SendError.NoError
AttributeError: 'EnumTypeWrapper' object has no attribute 'NoError'
```

**Comment by fenderle** [comment] 2020-04-28 15:53
Had the same - downgraded to the previous version...

**Comment by postlund** [comment] 2020-04-28 16:12
Duplicate of #623.

**Comment by postlund** [comment] 2020-04-28 16:12
(just pushed an update with a fix)

**Closed by postlund** 2020-04-28 16:12 UTC
Labels: bug
