### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by XMellOnsX** [postlund/pyatv#1517] opened 2021-12-09 22:09 UTC
### What's on your mind?

Hi i faced an issue that i cant understand, i have "Config flow could not be loaded" - error massage when i try to add apple tv int.

There is some screens from log and error window.

I will realy aprichiate if you can help me)

![image](https://user-images.githubusercontent.com/95884325/145483324-30228ad2-f235-4f37-828c-cd19f7ebee9a.png)
![image](https://user-images.githubusercontent.com/95884325/145483377-9f7b9f16-18d7-4546-8848-9729a88210ff.png)
![image](https://user-images.githubusercontent.com/95884325/145483401-cae08fe3-4ca1-4984-9cba-83d7736f73e3.png)
![image](https://user-images.githubusercontent.com/95884325/145483424-bbb2c6e5-6321-4b44-a0ee-a228b4d23f10.png)

P.S. - i will add errors text below.
------------------------------------------------------------------------------------------------------------------------------------------
Logger: aiohttp.server
Source: custom_components/apple_tv/config_flow.py:149
Integration: Apple TV
First occurred: 11:04:11 PM (3 occurrences)
Last logged: 11:06:57 PM

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/config_flow.py", line 59, in <module>
    class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
    self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'
----------------------------------------------------------------------------------------------------------------------------------------------Logger: homeassistant
Source: custom_components/apple_tv/config_flow.py:149
Integration: Apple TV
First occurred: 11:04:11 PM (5 occurrences)
Last logged: 11:06:31 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/util/async_.py", line 170, in gather_with_concurrency
    return await gather(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/util/async_.py", line 168, in sem_task
    return await task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/config_flow.py", line 59, in <module>
    class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
    self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'

**Comment by postlund** [comment] 2021-12-09 22:16
Duplicate of #1501.

**Closed by postlund** 2021-12-09 22:16 UTC
Labels: question
