### ISSUE TITLE
pyatv 0.9.8 not returning playing state

### ISSUE THREAD

**Issue by martijnkorteweg** [postlund/pyatv#1611] opened 2022-01-17 19:09 UTC
### What do you need help with?

Hi there,

I am kinda new to using pyatv, i got it to pair to my atv and able to send play/pause commands. Where its breaking down for me is the `playing` command. currently its always returning 

```
Media type: Unknown
Device state: Idle
```

I am running pyatv on my mac 

pyatv Version: 0.9.8
Python: 3.8.2
ATV:  Apple TV 4K, tvOS 15.2 build 19K53

Some help figuring this out would be greatly appreciated.

Thank you!

**Comment by postlund** [comment] 2022-01-17 20:37
I believe this is a duplicate of #1601. It seems to me that tvOS is acting up a bit as the iOS remote reports incorrect progress (but there's a bug in pyatv as well). Hopefully state will improve in a future version of tvOS.

**Comment by martijnkorteweg** [comment] 2022-01-17 21:12
ok thank you! i will track that ticket. hope there is a solution to this soon.

**Comment by postlund** [comment] 2022-01-19 11:54
By the way, which protocols did you pair and what credentials are you passing to `atvremote`?

**Comment by martijnkorteweg** [comment] 2022-01-25 05:48
i am pairing with airplay and companion and tried sending both credentials aswell as just airplay. on the scan it shows mrp is available but pairing with that doesn't work at all, just getting a timeout error

**Comment by martijnkorteweg** [comment] 2022-01-26 18:02
sending you an email with logs, it seems it thinks its using a different protocol then it actually is and returning wrong information because of it. the debug logs do show the play state information so its there just not being passed back

**Comment by postlund** [comment] 2022-01-31 20:27
Does iOS show the correct metadata? Did you use the `play_url` command by any chance? At a glance it looks like metadata is locked to AirPlay, which usually happens after using `play_url`. It kinda breaks metadata and all sorts of things. It's a bug in tvOS and only way to recover is to reboot the ATV.

**Comment by martijnkorteweg** [comment] 2022-02-01 02:01
Hey i must have, just rebooted ATV and it seems to be working now. thanks for helping with this.

**Comment by postlund** [comment] 2023-07-13 08:04
Will close, but likely not because of pyatv.

**Closed by postlund** 2023-07-13 08:04 UTC
Labels: question
