### ISSUE TITLE
TVOS 15 wont integrate

### ISSUE THREAD

**Issue by egobuster1** [postlund/pyatv#1475] opened 2021-11-23 01:20 UTC
### Describe the bug

Home Assistant finds the device but everytime i try and configure it i get 2 sets of codes to enter and after the second code it just says aborted and goes away. wont integrate.
ive even tried doing it manually by entering the IP address and does the same thing. 

### Error log

```log
Logger: custom_components.apple_tv.config_flow
Source: custom_components/apple_tv/config_flow.py:326
Integration: Apple TV
First occurred: 8:13:01 PM (1 occurrences)
Last logged: 8:13:01 PM

Authentication problem
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 54, in start_pairing
    resp = await self.protocol.exchange_opack(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/protocol.py", line 80, in exchange_opack
    unpacked_object, _ = opack.unpack(payload)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 126, in unpack
    return _unpack(data, [])
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 133, in _unpack
    if data[0] == 0x01:
IndexError: index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 326, in async_pair_next_protocol
    await self.pairing.begin()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/pairing.py", line 53, in begin
    await error_handler(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: index out of range
```

### How to reproduce the bug?

try and add the device

### What is expected behavior?

device to add

### Operating System

im using MacOS but home assistant is a virutal machine 

### Python

3.6

### pyatv

unkown 

### Device

Apple TV 4K

### Additional context

none

**Comment by postlund** [comment] 2021-11-23 04:37
Duplicate of #1466.

**Closed by postlund** 2021-11-23 04:37 UTC
Labels: bug
