### ISSUE TITLE
Controlling/Fetching Metadata from Apple Music app

### ISSUE THREAD

**Issue by wikewi** [postlund/pyatv#1172] opened 2021-06-23 21:28 UTC
Sorry if this question is a bit off-topic. With Apple Music's recent launch and inability of most Apple devices to properly play back Apple Music lossless files I was looking for ways to control the Apple Music app for macOS but haven't found any useful way other than relying on AppleScript. I wonder if you have any recommendations or insights on how to use existing protocols like DMAP to extract/handle data coming from the application? Would you be interested on making it part of pyatv or are there existing projects better suited for it?

**Comment by postlund** [comment] 2021-06-24 08:10
I don't think the Apple Music app has (on macOS) has any external network based API, so I don't immediately see any solution here. Maybe Companion can do it, not sure (but I don't have any way to get credentials to use that with the mac). It feels a bit out of scope, but I don't want to dismiss it yet either (I did that with the AirPort Express and see where we ended up...). Somewhat creative solutions are welcome, I don't fancy the idea of executing raw shell commands though (I need some kind of real API).

**Comment by Schlaubischlump** [comment] 2021-06-24 14:21
Which API ist the https://apps.apple.com/us/app/itunes-remote/id284417350 using ? There must be some API to fetch the metadata and control the playback.

**Comment by wikewi** [comment] 2021-06-24 15:48
> Which API ist the [iTunes Remote](https://apps.apple.com/us/app/itunes-remote/id284417350) app using ? There must be some API to fetch the metadata and control the playback.

Right a similar app would indeed be the most useful! But it seems like quite a tall order considering it's functionality. For now having simple playback control and metadata fetching options would help a lot. As Apple's remote app only runs on iOS and not even M1 Macs it's use is quite limited. There seems to have been client made for iOS by a third party but seemingly abandoned long ago using the DAAP protocol.

https://apps.apple.com/us/app/simple-daap-client/id369605270

There's even a fairly well known server package that emulates this:

https://github.com/jasonmc/forked-daapd

However on the client side I haven't seen any recent clients that work with Apple Music.

**Comment by Schlaubischlump** [comment] 2021-06-24 16:03
I searched a little bit and it seems that someone actually implemented this protocol in Ruby. It's called DACP

https://github.com/jurriaan/ruby-dacpclient

**Comment by postlund** [comment] 2021-06-24 17:21
That's interesting, didn't know that still works. The old iTunes remote app uses DACP as mentioned (maybe also supports MRP nowadays). It's the same as what I call DMAP in pyatv. I believe DMAP is the to seen as the underlying protocol that carries DACP and DAAP. Anyways, they are all three the same in this context. It's just the matter of which tags are used.

As I haven't tested it, I can't tell for sure, but pyatv might be able to support it already. Or close to it at least. @Schlaubischlump if you do `atvremote scan`, do you see your mac? Can you pair with it or control it (will work automatically if it has Home Sharing configured)?

**Comment by Schlaubischlump** [comment] 2021-06-24 18:27
I'll test it and report back

**Comment by postlund** [comment] 2021-06-25 18:41
@Schlaubischlump I just noticed that service myself, never seen it before. But I think you are on the right track, assuming that it's really DMAP/DAAP/DACP that is used. But apparently it seems like it. The volume thing sound like a bug or something, never noticed before. Since it's unencrypted, it should be easy enough to just sniff and see what the real app is doing. Maybe that gives some hints? Did metadata work with your changes btw?

**Comment by Schlaubischlump** [comment] 2021-06-25 20:07
It does seem to work, but there are a couple of warnings for unknown DMAP tags.

If I execute `atvremote --id "Mediathek" artist` I get: 

```Python
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'asai\x00\x00\x00\x08<\xb6*\x89\xd2\xc8\xa8\x9acmmk\x00\x00\x00\x04'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'aeGs\x00\x00\x00\x01\x01ceGS\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'ceGS\x00\x00\x00\x01\x01casa\x00\x00\x00\x04'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'casa\x00\x00\x00\x04\x00\x00\x00\x01aels\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'aels\x00\x00\x00\x01\x00aelb\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'aelb\x00\x00\x00\x01\x00astm\x00\x00\x00\x04'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'astm\x00\x00\x00\x04\x00\x02\xcf\x14casc\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'ceQu\x00\x00\x00\x01\x00'
John Lennon
```

Similar if I run `atvremote --id "Mediathek" title`:

```Python
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'asai\x00\x00\x00\x08<\xb6*\x89\xd2\xc8\xa8\x9acmmk\x00\x00\x00\x04'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'aeGs\x00\x00\x00\x01\x01ceGS\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'ceGS\x00\x00\x00\x01\x01casa\x00\x00\x00\x04'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'casa\x00\x00\x00\x04\x00\x00\x00\x01aels\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'aels\x00\x00\x00\x01\x00aelb\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'aelb\x00\x00\x00\x01\x00astm\x00\x00\x00\x04'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'astm\x00\x00\x00\x04\x00\x02\xcf\x14casc\x00\x00\x00\x01'
WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'ceQu\x00\x00\x00\x01\x00'
Imagine
```

**Comment by postlund** [comment] 2021-06-25 20:14
Yeah, that's likely gonna happen. In reality that warning can be ignored as it only means there's data I there I haven't seen before (this does not have any definition of or use for at this time). Just kept the waiting around so that people would create issues, letting me add new fields as they popped up. Some of the tags can probably be googled as well. All defined tags are in`pyatv/dmap/tag_definitions.py`.

Anyhow... the play/pause/audio-bug you ran into, can you replicate that multiple times? Does the same thing happen with the app?

**Comment by Schlaubischlump** [comment] 2021-06-25 20:20
Regarding the tags: 

https://github.com/mattstevens/dmap-parser/blob/master/dmap_parser.c
`asai`: `daap.songalbumid`
`aeGs`: `com.apple.itunes.can-be-genius-seed`
`aels`: `com.apple.itunes.liked-state`
`astm`: `daap.songtime`

I will try to reproduce the bug and report back.

**Comment by postlund** [comment] 2021-06-26 10:28
> Edit: The bug is reproducible, but it also happens for the iTunes Remote app. So this isn't related to pyatv.

It's always a mixed feeling when this is the case, but from a protocol perspective it's positive I guess. Will try to push a PR with the necessary changes later today. It's more or less the same changes to did @Schlaubischlump. Maybe you can try it out, @wikewi?

**Comment by wikewi** [comment] 2021-06-26 18:17
Sure let me know it's ready and I'll give it a try! Just tried playing and pausing with the iTunes remote app btw and didn't notice any volume change issue. I'm on Big Sur if that makes any difference...

**Comment by postlund** [comment] 2021-06-26 18:30
@wikewi An initial version is now in #1182, please let me know if it/what works!

**Comment by wikewi** [comment] 2021-06-26 19:31
Looks promising. It does seem to detect it when I scan it with the command 

> python3.7 atvremote.py scan

```
      Name: Audio Player
   Model/SW: Unknown Model ATV SW
    Address: 192.168.2.127
        MAC: None
 Deep Sleep: False
Identifiers:
 - 6D7C62F5EF439E24
Services:
 - Protocol: Companion, Port: 49547, Credentials: None
 - Protocol: DMAP, Port: 53340, Credentials: None
```

However when I run :

> python3.7 atvremote.py -i 192.168.2.115 artist

```
2021-06-26 21:29:39 ERROR [wikewi]: Could not find any Apple TV on current network
```

Am I doing something wrong?

**Comment by postlund** [comment] 2021-06-26 19:53
I guess it didn't find your "HSGID". It should be available if home sharing is enables. The instructions here should help you with that:

https://support.apple.com/en-us/HT202190

However... it would be interesting to try pairing, since I have no idea if that works. You can try:

    atvremote -s ip --protocol dmap pair

And see what happens. Hopefully you can enter a PIN somewhere.

**Comment by wikewi** [comment] 2021-06-26 20:03
> atvremote -s ip --protocol dmap pair 

seems to have worked though it did open up many instances of pairing in the Music app. It returned credentials after pairing. How can I use these for my next query? I'll try to read up the other article in the meantime...

**Comment by postlund** [comment] 2021-06-26 20:07
You pass the credentials via `--dmap-credentials <credentials>` when running `atvremote`. Should hopefully work right away 👍

**Comment by wikewi** [comment] 2021-06-26 20:26
It seems not yet. Couple of things to note though the pairing process launches quite a few of these sessions 
![Untitled](https://user-images.githubusercontent.com/60844543/123524798-e9da4380-d6cc-11eb-9c18-f63ebe1c1f1f.jpg)

When I try to run  atvremote.py --dmap-credentials 0xB8C7CBBxxxxxxxxx --id 6D7C62F5EF439E24 artist it still gives 

```
Traceback (most recent call last):
  File "atvremote.py", line 698, in _run_application
    return await cli_handler(loop)
  File "atvremote.py", line 487, in cli_handler
    return await _handle_commands(args, config, loop)
  File "atvremote.py", line 596, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "atvremote.py", line 634, in _handle_device_command
    playing_resp = await atv.metadata.playing()
  File "/usr/local/lib/python3.7/dist-packages/pyatv/support/facade.py", line 209, in playing
    return await self.relay("playing")()
  File "/usr/local/lib/python3.7/dist-packages/pyatv/dmap/__init__.py", line 449, in playing
    return await self.apple_tv.playstatus()
  File "/usr/local/lib/python3.7/dist-packages/pyatv/dmap/__init__.py", line 199, in playstatus
    resp = await self.daap.get(cmd_url, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/dmap/daap.py", line 114, in get
    return await self._do(_get_request, is_daap=daap_data)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/dmap/daap.py", line 149, in _do
    return await self._do(action, False, is_login=is_login, is_daap=is_daap)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/dmap/daap.py", line 151, in _do
    raise exceptions.AuthenticationError("failed to login: " + str(status))
pyatv.exceptions.AuthenticationError: failed to login: 501
```

However when I run  atvremote.py -s xxx.xxx.xxx.xxx scan
```
       Name: Audio Player
   Model/SW: Unknown Model ATV SW
    Address: xxx.xxx.xxx.xxx
        MAC: None
 Deep Sleep: False
Identifiers:
 - x
Services:
 - Protocol: Companion, Port: 49547, Credentials: None
 - Protocol: DMAP, Port: 53340, Credentials: 00000000-06a6-c561-cfxx-8bxxxxxxxxxx
```

It does now seem to list some credentials which it has stored I guess but the credentials are perhaps in a different format?

**Comment by postlund** [comment] 2021-06-26 20:36
Ok, that's interesting. Guess I need to troubleshoot that. The credentials that are automatically filled in comes from Home Sharing (it's the HSGID). It *should* work automatically if you have that set, no need to pass `--dmap-credentials` in that case. Still the same if you don't pass that?

**Comment by wikewi** [comment] 2021-06-26 20:49
Ok that's strange both using home sharing as well as using dmap pairings credentials seems to result in the exact same error:

> pyatv.exceptions.AuthenticationError: failed to login: 501

It's interesting as I have more devices only the ones recognising DMAP show these credentials (Music.app clients)

**Comment by postlund** [comment] 2021-06-27 17:38
> Ok that's strange both using home sharing as well as using dmap pairings credentials seems to result in the exact same error:
> 
> > pyatv.exceptions.AuthenticationError: failed to login: 501

That is interesting, can't really tell why that is. Would be great with someone else trying this, just to see if it's a one-off or more regular. @Schlaubischlump Do you by any chance have time to try my PR?

> It's interesting as I have more devices only the ones recognising DMAP show these credentials (Music.app clients)

Only DMAP has any kind of auto-detection of credentials (because of Home Sharing), so you will only see it for those devices. In the future, there will be persistent storage for credentials (amongst other things), when that is implemented you will se credentials for other protocols as well.

**Comment by Schlaubischlump** [comment] 2021-06-27 18:50
Hi @postlund, 

Just tested your branch. It's working fine for me. No pairing or anything else required, although I do have homesharing enabled. Playback control and metadata is both working.

**Comment by wikewi** [comment] 2021-06-27 18:53
@Schlaubischlump ok perhaps there's something wrong on my end then which version of the Music.app are you using. I'm using 1.1.5.74

**Comment by Schlaubischlump** [comment] 2021-06-27 18:55
Music.app 1.1.4.110 on mac OS Big Sur 11.3 (20E232), running pyatv on the same machine.

**Comment by wikewi** [comment] 2021-06-27 19:26
Ok I finally was able to use my gf's machine who luckily hasn't updated to the last Apple Music yet. Seems to work fine there. So it seems to be broken as of 1.1.5.74 11.4 (which is unfortunate as that is the version that starts supporting apple lossless, though I doubt that has anything to do with it)

atvremote.py --id FCFxxxxxxx playing
2021-06-27 21:24:30 WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'casa\x00\x00\x00\x04\x00\x00\x00\x01aels\x00\x00\x00\x01'
2021-06-27 21:24:30 WARNING [pyatv.dmap.tag_definitions]: Unknown data: b'aelb\x00\x00\x00\x01\x00astm\x00\x00\x00\x04'
  Media type: Unknown
Device state: Playing
       Title: Summer Anthem
      Artist: Bernward Koch
       Album: Filled with Light
       Genre: New Age
    Position: 8/375s (2.1%)
      Repeat: Off
     Shuffle: Off

**Comment by Schlaubischlump** [comment] 2021-06-27 19:28
Is the iTunes Remote app broken as well ?

**Comment by wikewi** [comment] 2021-06-27 19:28
No it's working fine on all clients

**Comment by postlund** [comment] 2021-06-27 19:54
Then we need to sniff the traffic and see what has changed.

**Comment by Schlaubischlump** [comment] 2021-06-27 20:47
I can try to sniff the traffic for the working music app, but I don't have the new music app with lossless support. Is this version out of beta yet ? Otherwise it might be a good idea to wait until its out of beta.

**Comment by wikewi** [comment] 2021-06-27 20:49
Actually it's part of macOS Big Sur 11.4 it's not beta I think you should just be able to update.

**Comment by Schlaubischlump** [comment] 2021-06-27 21:37
Strange mac OS is telling me 11.3 Beta 3 is the latest version. Maybe I find the update if I remove the beta profile.

**Comment by postlund** [comment] 2021-06-28 08:27
I just upgraded myself, got the same problem. Looked at the traffic and now it seems like FairPlay is used for authentication, e.g.:

    GET /login?hasFP=1&hsgid=xxx HTTP/1.1
    POST /fp-setup?session-id=xxx HTTP/1.1
    POST /fp-setup?session-id=875395223&hsgid=xxx HTTP/1.1
    GET /home-share-verify?hspid=0&session-id=875395223&hsgid=xxx HTTP/1.1

I'm not sure this has been reverse engineered properly yet or not. So we might be stuck, unless we can use another authentication method. We need to dig deeper into this.

**Comment by Schlaubischlump** [comment] 2021-06-28 10:37
Does FairPlay authentication require any special hardware component ? If we use the oldest available mac that can still run mac OS 11.4, is there a changes that fairplay can not be used in this setup. This might help to find a different authentication method, if one is available.

**Comment by wikewi** [comment] 2021-06-28 11:18
I doubt that actually the main Mac I'm testing this on is a 2012 Mac mini that was updated using a Big Sur patcher (technically that Mac mini doesn't even support Big Sur). Either way it also happens on a 2018 model so the results seem the same so I don't think there's any hardware involved here.

**Comment by postlund** [comment] 2021-06-28 11:39
I am fairly certain this is only software based (it could still have been broken even if it was hardware based). Might be worth a shot to see if the legacy authentication used by AirPlay works or even HAP (like all the other protocols nowadays, more or less). Requires a bit of work to verify though.

**Comment by postlund** [comment] 2021-06-29 18:38
I did some research yesterday and played around a bit. From what I've gathered:

* FairPlay has not been fully reverse engineered
* There are "solutions" out there however, which loads the dylib and calls the "real" functions in Apples implementation
* Legacy pairing does not seem to be supported, nor HAP

I'm not sure where to go from here. Properly reverse engineering is of course what we need to do, but since no one has properly done that yet I bet that will not happen anytime soon. Or it could happen by tomorrow, no way of knowing (I'm certainly not capable of it though).

**Comment by postlund** [comment] 2021-06-29 18:42
And I just want to clarify that by "not been fully reverse engineered", I mean publicly, I.e. something we can find and implement. Any closed solutions aren't really relevant here.

**Comment by Schlaubischlump** [comment] 2021-06-29 21:07
I thought about jailbreaking my iPhone 6s (don't know if checkra1n already supports 14.7), dumping the iTunes Remote app and loading it inside Hopper, to see if the source code includes some hints about the available authentication methods. This does require a little bit of time and its been a while since I've last done this. So this might be way more difficult than I remember. I might have time on the weekend. I don't think I'm able to reverse engineer the fairplay protocol by myself, but maybe there is some  other authentication way implemented inside the app.

**Comment by wikewi** [comment] 2021-06-29 22:18
Ok I can see this is taking a pretty serious turn. While I very much do appreciate the effort and personally wouldn't be surprised if Apple would implement this authentication in the future on tvOS as well. I now feel it is order to remark on the reason for asking my question. The introduction of Apple lossless is fairly recent (a month old). It has left many users in limbo on how to actually properly play back this format. There is a weird issue with Apple lossless currently.

- The Music files support 24bit 192KHz format
- Recent Apple hardware has no SP/DIF output thus leaving many users unable to properly play back these files (this being the reason I use my old Mac mini as it is still able of outputting high resolution audio)
- Airplay currently is also unable to support audio beyond 24bit 44KHz

This has left a strange gap where only older machines can directly playback the audio but newer machines can't without adding a USB DAC/HDMI audio splitter. Either way I look at it most users will need a _"certain"_ device that is able to play back these files and preferably being able to remote control that machine. This would be where I can see pyatv being very useful!

I wouldn't be surprised if Apple were to _resolve_ this issue by introducing hardware that is capable of doing this. At this point I also wouldn't be surprised if Apple were to announce airplay 3 sometime soon to support this high resolution format. macOS Monterey has a Airplay receiver built-in to the OS as well so this might be a hint to where this is headed. Either way it seems likely changes are bound to happen that of course could have impact on pyatv as well. It's just a bit early and soon to tell perhaps. Not that I'm not interested to see this work progress. Just adding my 2 cents :)

**Comment by Schlaubischlump** [comment] 2021-06-29 23:20
Just a quick update. I used my old iPhone 5 running iOS 9.0.2 to extract and old version of the Remote.app. This version is still compatible with the Music app on Big Sur (haven't tested with 11.4 yet since my Mac is still updating, but is working fine for 11.3).  Hopper can open the extracted file. The app does seem to implement an `fpSetup` function. It's late, but I might look into it in the coming days. I don't expect much from it, since I'm far from being an expert in reverse engineering, but it still might be worth a look.

**Comment by postlund** [comment] 2021-06-30 14:05
@wikewi That's an interesting read, thanks for explaining that. Didn't know how complicated this really is. The important part for me is the technical part, I.e. getting the remote support working. We will have to dig deeper and see if we can find a way, hopefully we will.

@Schlaubischlump Interesting findings! I suggest that you sniff the traffic with wireshark in various situations, it might tell us something l. Probably when support for FairPlay authentication is my best guess.

**Comment by postlund** [comment] 2021-09-14 12:32
So, I'm on macOS 11.5.1 (Music 1.1.6.32) and it seems to work again. I can control playback and get push updates. Can anyone else confirm this?

**Comment by Schlaubischlump** [comment] 2021-09-14 14:29
I'm still on 11.4. I'll update my mac to 11.6 this evening and let you know if it works.

**Comment by postlund** [comment] 2021-09-15 06:33
Thanks for verifying @Schlaubischlump! I will update the documentation regarding this 👍

**Closed by postlund** 2021-09-15 06:33 UTC
Labels: question, dmap
