### ISSUE TITLE
Status Command

### ISSUE THREAD

**Issue by samsonrosen** [postlund/pyatv#125] opened 2017-11-17 19:31 UTC
Hi, is it possible to check the status of the Apple TV. Whether it's on or off etc.

**Comment by postlund** [comment] 2017-11-17 20:00
I assume that you use CEC and want to avoid waking the device up by checking its status? That is unfortunately not possible.

**Comment by jlian** [comment] 2018-02-11 09:13
Hi @postlund I've scoured the entire internet and it seems like there's no way to detect the state (on/standby) of an Apple TV over DAAP. Do you know if it's possible via MRP?

**Comment by postlund** [comment] 2018-02-12 15:37
@jlian Yes, that seems to be about right. If I remember correctly it's the same behavior with MRP (it's the TCP-connection that wakes the devise) so I think it's the same state with MRP. So the answer is back no.

**Comment by jlian** [comment] 2018-02-12 19:08
@postlund damn, that's too bad. Currently I'm running into the issue where I can turn the Apple TV on via homebridge+HomeKit, but if the Apple TV gets turned off via the remote then it would still show as "on" in HomeKit. This breaks automation scenarios that I want to set up (when person X arrives home, turn on Apple TV) because HomeKit doesn't send another command if it thinks the Apple TV is already on.

Thanks though! I wonder if there's any way around this.

**Comment by postlund** [comment] 2018-02-13 10:59
Do you use Home Assistant? I guess it would be possible to alter state so that if no connection is open, it reports as "off". My solution is to never turn it off via the remote. It will turn off automatically after a while anyway (I don't use CEC).

**Comment by jlian** [comment] 2018-02-13 18:02
I don’t, I’m only using homebridge right now. I’d imagine what your describe is probably doable in homebridge too, I’ll have to take a look

**Comment by postlund** [comment] 2018-02-14 14:43
Ok! Just because I'm curious, how did you integrate it with home bridge? H
Just calling shell commands?

**Comment by jlian** [comment] 2018-02-14 19:14
Today I'm using [homebridge-harmony](https://www.npmjs.com/package/homebridge-harmonyhub) but I've been looking for a better solution - one helps HomeKit to stay in sync with Apple TV's on/standby status - either with [homebridge-cmdswitch2](https://www.npmjs.com/package/homebridge-cmdswitch2) (shell commands) or [homebridge-http](https://www.npmjs.com/package/homebridge-http) (http requests). Both of these commands can integrate with HomeKit and check for status via polling, that's why I'm looking for a what http request I should send to check status of an Apple TV

**Comment by JohnnyBBravo** [comment] 2019-02-27 13:28
Hi, sorry to revive this old thread.

I'm also looking for a way to detect if my Apple TV is on or asleep. I was just wondering perhaps if this is now a possibility (perhaps in newer TvOs or so?) 
I'm also working on integrating my AppeTV in my home automation project (OpenHAB) and would like to have the ability to detect if it's on or asleep.

Thanks!

**Comment by postlund** [comment] 2019-02-27 13:36
Nope, no change in this area!

**Comment by JohnnyBBravo** [comment] 2019-02-27 13:47
That's a shame....but thanks for letting me know.

**Comment by postlund** [comment] 2019-10-03 05:45
This is really a duplicate of #49, so will close now.

**Closed by postlund** 2019-10-03 05:45 UTC
