### ISSUE TITLE
Remote Command in Home Assistant: select_hold

### ISSUE THREAD

**Issue by jeffjumper** [postlund/pyatv#2056] opened 2023-06-15 17:32 UTC
### What feature would you like?

Would it be possible to make a select_hold command for the AppleTV remote available in Home Assistant? This would be useful to be able to delete or move apps on the Home Screen as well as certain in app behavior. Currently it appears as if home_hold is the only hold command supported. 

I saw in #1854 that this is supported programmatically but I would love if select_hold could be added for use in Home Assistant also.

Thanks for all your work keeping this integration running!

### Describe the solution you'd like

Select_hold command that will send a long press of the select button to AppleTV via the remote in Home Assistant

### Any other information to share?

N/A

**Comment by postlund** [comment] 2023-06-24 09:32
Holding `select` is possible via `InputAction.Hold` and should be pretty easy to implement. I think the remote component has a `hold_secs` argument that can be used to implement this. I don't put that much time into the integration right now, but I can probably fix it some time in the future. Unless someone else does it first.

**Comment by postlund** [comment] 2023-07-11 05:05
This is really a duplicate of #1720, so I'll refer to that issue instead.

**Closed by postlund** 2023-07-11 05:05 UTC
Labels: feature, 3rd party
