### ISSUE TITLE
Power controls for real

### ISSUE THREAD

**Issue by notabene00** [postlund/pyatv#1352] opened 2021-09-29 11:03 UTC
### What feature would you like?

I want to power on/off my TV via this component and see the corresponding states

### Describe the solution you'd like

I tried something like this:
`self._powered_on = (self.atv.power.power_state == PowerState.On)` to set initial state when device connected
`atv.power.listener = self` with callback working fine for me (aTV 4k 1gen)
in this callback set new state (converted to boolean) to `self._powered_on `
`if self.atv is None or not self._powered_on` return STATE_OFF
`atv.power.turn_on()` turns device on
`atv.power.turn_off()` turns device off

### Any other information to share?

Hello from Russia, here we have voice assistant, Alisa, something like Siri in Apple ecosystem, but by Yandex - would like to use it to turn off all the devices when leaving living room just with one phrase.
For now I should have a component for my TV, cable from TV to router just to have the ability to turn it off. After which the TV is going to deep sleep without connection to router and turning on is possible with the IR remote or HDMI CEC only.

Solution described above fully solves my problem with turning on and off, also, the state of `media_player.livingroom_tv` (apple tv) is now` off` when it off, not `idle`.

**Comment by notabene00** [comment] 2021-09-29 11:06
Just to clarify. It is already working for me. Why should not all others use it like this?

**Comment by postlund** [comment] 2021-09-29 11:26
There is already a PR about adding power support to the Home Assistant integration here:

https://github.com/home-assistant/core/pull/51520

I'm still a bit hesitant about it, but people wants it so it will be merged and things might work to some extent. The problem is that `power_state` is not reliable: it *will* return incorrect values under some circumstances. One such circumstance is when using an external speaker, like a HomePod, for audio output. It will always return "on" in this case, until the connection between the device is lost for some reason.

Then we have the definition problem: what does "off" *really* mean? Is it physically off, like no power at all? Is it deep sleep/suspended, so that it is not on but can be awoken (e.g. via WoL)? How would we practically detect any of these cases? If we try to connect to it but that fails, does that mean it is off? If it is suspended and we wake it up by connecting to it, then what? If someone puts the device to sleep, closing the connection: should we try to recover (in case this was a connection problem, we can't really know) or just ignore it and let the device be a sitting duck as we would wake it up immediately by trying to connect to it (i.e. not "off" anymore)?

What do we do about devices that does not support power state, like Apple TV 3 (and earlier) or AirPlay receivers? The API that pyatv provides is generic for all of this, but we need to provide a behavior that seems reasonable, stable and makes sense for all devices no matter what they support. That makes this problem *really* hard to implement. You have one particular case and it works in your setup, but there are lots of different devices and setups that must also work. That is why support for this has taken a lot of time and still will be far from good, even with the mentioned PR merged.

**Comment by notabene00** [comment] 2021-09-29 14:05
> power_state is not reliable: it will return incorrect values ​​under some circumstances. One such circumstance is when using an external speaker

Sad to hear that. Maybe, it's not the worse thought to create a switch in the `config_flow` then?
Disabled is for current implementation, activated is for suggested in the subject.

> Then we have the definition problem: what does "off" really mean? Is it physically off, like no power at all?

In my picture of the world, `off` in HA means state in which device is not running its main function and can be turned on remotely.
Like the smart plug is `off` when relay has cut the power circuit, but the plug is not taken off the socket.

> If we try to connect to it but that fails, does that mean it is off?

For physically off devices (including `device not responding` cases), it should be`unavailable`, because in this case we can't do anything with that device remotely.
About other ... okay, it is way more complicated than I supposed.

> What do we do about devices that does not support power state, like Apple TV 3 (and earlier) or AirPlay receivers?

Back to current implementation without options.

Creating separate classes with overrided methods for such devices and use them respectively can be easier than trying to incapsulate logic of `_is_feature_available` in single class.

**Comment by dborup** [comment] 2021-10-05 19:08
> Just to clarify. It is already working for me. Why should not all others use it like this?

Hi. Can you guide me to the same setup?

**Comment by postlund** [comment] 2023-07-11 09:52
A lot if work has been done with regards to power management, so I think this should work now. Please open new, more specific issues in case you run into anything.

**Closed by postlund** 2023-07-11 09:52 UTC
Labels: feature, 3rd party
