### ISSUE TITLE
Application Launch

### ISSUE THREAD

**Issue by mschwartz** [postlund/pyatv#932] opened 2021-01-15 00:00 UTC
**What feature would you like?**
Is there any way to launch an application directly via the API?

An API call to launch an arbitrary App.  Like launch("Netflix") or Launch("Prime Video").

**Describe the solution you'd like**

The launch API.  A list API that lists the available (installed) Apps.

**Any other information to share?**

I didn't look at any remote control software to see if it's possible.  I do know I can use API for LG TV and Bravia TV to list and launch apps.

**Comment by postlund** [comment] 2021-01-15 05:46
Duplicate of #303.

**Closed by postlund** 2021-01-15 05:46 UTC
Labels: feature
