### ISSUE TITLE
Lost all control of Apple TV's/New TV's are not configured properly

### ISSUE THREAD

**Issue by MXNPD** [postlund/pyatv#705] opened 2020-06-08 19:25 UTC
**Describe the bug**
Upon updating to the latest version of the integration, none of my Apple TV's respond in Home Assistant.

**To Reproduce**
Update the plugin

**Expected behavior**
Apple TV's should just come back online.

**System Setup (please complete the following information):**
 - OS: [HassOS]
 - Python: [unknown]
 - pyatv: [0.6.1 update 3]
- Apple TV: [Apple TV 4th Gen and 5th Gen running Running 13.4]

**Additional context**
When trying to delete and readd an Apple TV, it does work properly either, upon deleting an Apple TV, it shows back up in the integrations, pairing codes initiate, and set's up, but then the integration itself shows no data. No devices or entities. And if it is any help at all, we have 20 Apple TV's that are integrated. I have also already rebooted Home Assistant, and attempting to reinstall the plugin.

**Comment by postlund** [comment] 2020-06-08 19:33
You need to update to Home Assistant 0.110 for it to work.

**Comment by MXNPD** [comment] 2020-06-08 21:49
> 
> 
> You need to update to Home Assistant 0.110 for it to work.

It appears I am on the latest version already sadly, I am running  0.110.5  as of right now

**Comment by postlund** [comment] 2020-06-09 05:12
Hmm, that's odd. The only change I made in the latest push adjustments to the name change in Home Assistant. I  will need some logs to troubleshoot further. Do you see any entries under Developer Tools -> Logs that might be related?

**Comment by MXNPD** [comment] 2020-06-09 05:19
> 
> 
> Hmm, that's odd. The only change I made in the latest push adjustments to the name change in Home Assistant. I will need some logs to troubleshoot further. Do you see any entries under Developer Tools -> Logs that might be related?

I was able to find some logs on it and have posted it below.

Below is an error for setting up remotes it says (and says it shows up 22 other times)

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/remote/__init__.py", line 117, in async_setup_entry
    return await cast(EntityComponent, hass.data[DOMAIN]).async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
    platform_type,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 247, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 279, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/remote.py", line 24, in <module>
    class AppleTVRemote(remote.RemoteEntity):
AttributeError: module 'homeassistant.components.remote' has no attribute 'RemoteEntity'`

Below this was labeled as an authentication problem.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyatv/support/__init__.py", line 29, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/auth.py", line 69, in finish_pairing
    pairing_data = _get_pairing_data(resp)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/auth.py", line 18, in _get_pairing_data
    raise exceptions.AuthenticationError("got error: " + str(error))
pyatv.exceptions.AuthenticationError: got error: 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 297, in async_step_pair_with_pin
    await self.pairing.finish()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/pairing.py", line 55, in finish
    self.pin_code,
  File "/usr/local/lib/python3.7/site-packages/pyatv/support/__init__.py", line 37, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: got error: 2`

Then below this is an issue with the TV that I tried to delete, and then readd 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 295, in async_unload
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 337, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 180, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!`

**Comment by postlund** [comment] 2020-06-09 10:07
> Below is an error for setting up remotes it says (and says it shows up 22 other times)
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
>     hass, self
>   File "/usr/src/homeassistant/homeassistant/components/remote/__init__.py", line 117, in async_setup_entry
>     return await cast(EntityComponent, hass.data[DOMAIN]).async_setup_entry(entry)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
>     platform_type,
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 247, in async_prepare_setup_platform
>     platform = integration.get_platform(domain)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 279, in get_platform
>     f"{self.pkg_path}.{platform_name}"
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/custom_components/apple_tv/remote.py", line 24, in <module>
>     class AppleTVRemote(remote.RemoteEntity):
> AttributeError: module 'homeassistant.components.remote' has no attribute 'RemoteEntity'
> ```

`RemoteDevice` was renamed to `RemoteEntity` in 0.110.0 (and some earlier betas of course), which was something I corrected in my latest push as I mentioned above. Since the component fails to find this import, we know that the component itself has been upgraded correctly but I am still 99% certain that you are not running 0.110 or later. I'm gonna upgrade to the latest version myself and see if I can reproduce.

> Below this was labeled as an authentication problem.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/pyatv/support/__init__.py", line 29, in error_handler
>     return await func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/auth.py", line 69, in finish_pairing
>     pairing_data = _get_pairing_data(resp)
>   File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/auth.py", line 18, in _get_pairing_data
>     raise exceptions.AuthenticationError("got error: " + str(error))
> pyatv.exceptions.AuthenticationError: got error: 2
>
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/apple_tv/config_flow.py", line 297, in async_step_pair_with_pin
>     await self.pairing.finish()
>   File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/pairing.py", line 55, in finish
>     self.pin_code,
>   File "/usr/local/lib/python3.7/site-packages/pyatv/support/__init__.py", line 37, in error_handler
>     raise fallback(str(ex)) from ex
> pyatv.exceptions.PairingError: got error: 2
> ```

This suggests that some part of the verification process failed, something I don't think I have seen before. Is this reproducible?

> Then below this is an issue with the TV that I tried to delete, and then readd
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 295, in async_unload
>     hass, self
>   File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 337, in async_unload_entry
>     return await hass.data[DOMAIN].async_unload_entry(entry)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 180, in async_unload_entry
>     raise ValueError("Config entry was never loaded!")
> ValueError: Config entry was never loaded!
> ```

This is related and most likely caused by the first issue.

**Comment by postlund** [comment] 2020-06-09 10:32
Just finished upgrading and no problem on 0.110.6 at least (with latest component version).

**Comment by postlund** [comment] 2020-06-15 10:24
Did you manage to get any further here or is it still the same problem?

**Comment by postlund** [comment] 2020-07-13 16:35
Will close this issue now, feel free to open if issue persists.

**Closed by postlund** 2020-07-13 16:35 UTC
Labels: 3rd party, bug
