### ISSUE TITLE
Support streaming HLS audio stream over RAOP

### ISSUE THREAD

**Issue by ha0y** [postlund/pyatv#1262] opened 2021-08-24 16:42 UTC
**What feature would you like?**
Support streaming HLS audio stream over RAOP

**Describe the solution you'd like**
See below.

**Any other information to share?**
I'm currently using Logitech Media Server with [LMS-to-Raop](https://github.com/philippe44/LMS-to-Raop) to stream radio channels to my HomePod. That plugin also implements RAOP and uses a dependency named `PlayHLS`(can't find links about it). Hope that pyatv also support it.

BTW: That plugin also does not support controlling play/pause. May link to https://github.com/postlund/pyatv/issues/1068 .

**Comment by postlund** [comment] 2021-08-24 17:40
I guess that it should be possible to implement that pretty easily, assuming there's a library that can deliver the audio chunks to pyatv. Definitely something worth supporting I would say. In the meantime, it should be possible to accomplish something similar by piping output from ffmpeg to pyatv, like the last example here:

https://pyatv.dev/documentation/atvremote/#streaming

**Comment by ha0y** [comment] 2021-09-23 16:06
Hey that's amazing! The following command line just works. It streams audio to my HomePod flawlessly. So maybe I just need to write a custom component for Home Assistant to get it work. 

`ffmpeg -i http://xxx.xxx.cn/live/dszs/index.m3u8 -f mp3 - | atvremote --id F4:34:xx:xx:xx:xx --debug stream_file=-
`

And if we deliver the audio chunk from ffmpeg to atv device simultaneously, we can implement that `synchronization`? I can't wait for that!

**Comment by postlund** [comment] 2021-09-24 20:44
Nice to hear that you have it working 😄 

Synchronized output requires implementation at protocol level that I think is pretty tricky. But should be possible I hope. Some day I might give it a try!

**Comment by postlund** [comment] 2021-10-08 11:47
I will see this as a duplicate of #1122 and close for now!

**Closed by postlund** 2021-10-08 11:47 UTC
Labels: feature, raop
