### ISSUE TITLE
There are some noise after playback finished

### ISSUE THREAD

**Issue by georgezhao2010** [postlund/pyatv#1254] opened 2021-08-14 19:21 UTC
I used stream.stream_file to play a audio file to my HomePod, there are some noise when playback finished, sounds like "Kahta".

```
async def stream_file(event_loop):
    atvs = await pyatv.scan(LOOP, hosts=["192.168.1.227"])
    if len(atvs) == 0:
        print("No device found")
    else:
        atv = atvs[0]
        atv_interface = await pyatv.connect(atv, event_loop)
        try:
            await atv_interface.stream.stream_file("1.wav")
            await asyncio.sleep(1)
        except Exception as e:
            print(e)
        atv_interface.close()

if __name__ == '__main__':
    LOOP.run_until_complete(stream_file(LOOP))
```
[audio file](https://github.com/postlund/pyatv/files/6987101/1.zip)

**Comment by postlund** [comment] 2021-08-18 10:32
I will have a look at that and see what I can do. Thanks for reporting!

**Comment by postlund** [comment] 2021-09-13 21:01
I have not managed to figure out exactly what is happening (but I can reproduce your behavior). So far I suspect it has to do with sync packets, but I can't confirm that yet. Will have to continue investigating.

**Comment by postlund** [comment] 2021-09-14 10:16
I experimented a bit more yesterday and I think I found a solution. My suspicion regarding sync packets was correct. There's a built-in latency in AirPlay and Apple uses two seconds (2,25 in AirPlay 2) whilst I use 1,5s (for some reason). I'm sending incorrect sync packets during that time period. I have made a change so that I send empty audio in order to maintain proper sync and it seems to work as expected. If I understood that code correctly, that seems to be what Owntone does as well. I'll try to have something ready to test by tonight. Can you try from a PR or do you want me to prepare a docker image?

**Comment by postlund** [comment] 2021-09-14 15:54
PR #1307 should hopefully fix this!

**Comment by postlund** [comment] 2021-09-20 12:53
@georgezhao2010 Can you verify if #1307 solves your problem?

**Comment by postlund** [comment] 2021-09-28 11:08
This has been shipped, I will close the issue now!

**Closed by postlund** 2021-09-28 11:08 UTC
Labels: bug, raop
