### ISSUE TITLE
Hass integration: "nothing playing"

### ISSUE THREAD

**Issue by DarKOrange75** [postlund/pyatv#848] opened 2020-10-05 07:06 UTC
**Describe the bug**
1 - The Apple TV Lovelace card no longer shows the snapshot and shows "nothing playing" instead.
2 -The button "play" no longer works and when clicked a message appears in the lower left corner "failed to call service media_player/media_play"

**To Reproduce**
1 - open Lovelace Apple TV card
2 - Click on the play button in the Lovelace card

**Expected behavior**
1 - display a snapshot of the currently playing content
2 - play or pause the Apple TV

**System Setup (please complete the following information):**
 - OS: HassOS 4.13 on Rpi 4
 - Python: 3.8.5
 - pyatv: Apple TV Beta Component latest
- Apple TV: Apple TV 4K tvOS 14.0.1

**Additional context**

TTS is working

<img width="393" alt="Capture d’écran 2020-10-05 à 09 06 22" src="https://user-images.githubusercontent.com/40524270/95049449-1044f280-06ea-11eb-98f0-6a1e48c817d4.png">

Thank you for your help!

**Comment by postlund** [comment] 2020-10-07 10:13
I think I might have found one potential reason for this. Assume it's new because of tvOS 14. Will try to catch up with pyatv and Home Assistant integration in near time.

**Comment by DarKOrange75** [comment] 2020-10-07 10:26
Thank you Pierre :)

**Comment by postlund** [comment] 2020-10-08 08:28
New update is out now, please try it when you have time!

**Comment by marima84** [comment] 2020-10-08 08:43
@DarKOrange75 in my case updating to last version 0.7.3 fixed the issue.

Mark

**Comment by DarKOrange75** [comment] 2020-10-09 08:04
Unfortunately this did not fix my issue :-( I deleted the previous version and installed the latest one. The text on the card has changed but no snapshot and actions return an error message, see pictures.

**Comment by postlund** [comment] 2020-10-09 08:14
Is something playing via AirPlay at this point, or is it paused? Can you start playing from iOS for instance? The error (ApplicationNotFound) is returns by the device if an action, like play, is sent and no application is running that is able to handle that.

**Comment by DarKOrange75** [comment] 2020-10-09 08:53
Nothing is playing via AirPlay, the AppleTV is on and reading a TV feed, previously in this case the card was displaying a snapshot of the program playing on the TV and I was able to pause the app installed on the TV playing the TV feed.

Now I've tried to playing something from iOS via Airplay, in this case the commands on the Lovelace card work and are pausing the stream. Still no snapshot though.

One thing I noticed when reinstalling is that the TV is showing a code 3 times and there is no way to enter the 3rd one (remote authentication) in Hass configuration panel, instead it is showing the room choice menu for the configured TV

**Comment by postlund** [comment] 2020-10-09 11:18
Might be that I parse the state wrong. Does it show correct in iOS, e.g. the remote app? What would be helpful to me is the output of `atvremote -s <atv ip> --debug playing` when this happens.

What protocol does it say for the third PIN? I guess, in the end, I need some logs to understand what's happening. If you enable that and try pairing again and upload the logs here I can take a look.

**Comment by DarKOrange75** [comment] 2020-10-09 11:55
My knowledge of Home Assistant may be too limited unfortunately 😩

<img width="602" alt="Capture d’écran 2020-10-09 à 13 34 42" src="https://user-images.githubusercontent.com/40524270/95580117-12cf8100-0a37-11eb-84a3-64fb873ba351.png">

**Comment by postlund** [comment] 2020-10-11 20:12
I'm not sure running for HA like that is such a great idea. It's probably easiest if you install it on another computer on the same network.

**Comment by postlund** [comment] 2020-10-12 09:04
Also, I have found the reason why you get an additional PIN dialog. Or rather, why the initial one does not disappear. See #861 for details.

**Comment by DarKOrange75** [comment] 2020-10-12 14:11
OK thank you Pierre :-)

**Comment by Jolle666** [comment] 2020-11-22 21:23
Hi, just wanted to add, that I've had the integration worked great for a couple of days. Suddenly I experienced this error. Tried to remove and reinstall the component several times with no luck. A simple restart of the Apple TV fixed the problem for me.

**Comment by postlund** [comment] 2020-12-05 12:21
@Jolle666 Can you please try to get me some debug logs to help me troubleshoot?

**Comment by postlund** [comment] 2020-12-05 12:25
@DarKOrange75 Maybe you can try to run `atvremote` on another computer instead? You could also thanked logging in Home Assistant and attach it here.

```yaml
logger:
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```

**Comment by DarKOrange75** [comment] 2021-01-02 21:44
Just to let you know that it is working now, I don't know why... thinly problem is that when a program changes on the TV it doesn't automatically update the Lovelace card, I need to click on a command in this card to update it.

**Comment by k-rock** [comment] 2021-02-05 04:16
![Screen Shot 2021-02-04 at 10 43 55 PM](https://user-images.githubusercontent.com/15674791/106987359-413a4000-673b-11eb-8612-d9922b1cc955.png)

Hi - I think I am noticing the same behavior:

**Describe the bug**
The entity state is not changing & cover art is not shown on Lovelace card

**To Reproduce**
Playing video in ATV with apple remote.

**Expected behavior**
The entity state updates (paused -> play) & cover art is displayed on Lovelace card

**System Setup**
OS: Debian GNU/Linux 10 (buster), Docker version 20.10.3, core-2021.2.0, supervisor-2021.01.7
Python: Python 2.7.16
pyatv: Apple TV Beta Component latest
Apple TV: Apple TV 4K tvOS 14.4

I have added the logger to my configuration.yaml file - what should I look for there?
my log is quite large .. too large to paste here. 

> ```yaml
> logger:
> logs:
>  pyatv: debug
> custom_components.apple_tv: debug
```

Thanks!

**Comment by postlund** [comment] 2021-02-05 06:26
@k-rock Can you please try running without the custom component and use the built in version instead? It has received a lot more fixes. I will try to synchronize the beta repo so it contains the same code as what is bundled with Home Assistant anyways.

**Comment by k-rock** [comment] 2021-02-05 14:05
![image](https://user-images.githubusercontent.com/15674791/107043576-33170e80-6791-11eb-98e2-5078ec5b1efa.png)

@postlund - sure, i can do that - thanks!

However, I keep receiving an error that my Apple TV is already configured... I removed the HACS beta integration and I do not have any entities configured related to Apple TV - any ideas here? thanks!

**Comment by k-rock** [comment] 2021-02-05 21:47
ok - i found my issue..  old entries in homeassistant/.storage/core.config_entries. I removed those and was able to set up the integration. Thanks!

**Comment by k-rock** [comment] 2021-02-07 23:53
It's working now! Not sure what changed but it works :)

**Comment by postlund** [comment] 2021-02-08 11:30
Did you upgrade in HACS? I pulled the code from Home Assistant core repository yesterday and pushed as a release, that might have helped. It's the exact same code as will be in the next release (2021.3.1). So I suggest that you remove the beta repo from HACS once that release is out and you have upgraded. I will not put any focus on the beta repo for a while.

**Closed** 2021-06-16 12:04 UTC
Labels: bug
