### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by wayller** [postlund/pyatv#878] opened 2020-11-23 18:42 UTC
- pyatv: 0.7.4
- Apple TV: Apple TV 4K tvOS 14.2

atvremote scan --debug
```
/config # atvremote scan --debug
2020-11-23 19:40:31 DEBUG: Binding on *:5353
2020-11-23 19:40:31 DEBUG: Binding on 127.0.0.1:5353
2020-11-23 19:40:31 DEBUG: Binding on 10.0.150.25:5353
2020-11-23 19:40:34 DEBUG: Auto-discovered TV-rom at 10.0.0.102:7000 (Protocol.AirPlay)
Scan Results
========================================
```

atvremote scan --debug --mdns-debug
```
/config # atvremote scan --debug --mdns-debug
2020-11-23 19:40:40 DEBUG: Binding on *:5353
2020-11-23 19:40:40 DEBUG: Binding on 127.0.0.1:5353
2020-11-23 19:40:40 DEBUG: Binding on 10.0.150.25:5353
2020-11-23 19:40:40 DEBUG: Sending multicast DNS request to 224.0.0.251:5353 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:40 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:40 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:41 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000084000000000600000000085f616972706c6179045f746370056c6f63616c00000c00010000119400090654562d726f6dc00c0e5f6d6564696172656d6f74657476c015000c000100001194000d0a73747561202837353229c034c034000c000100001194001411736f7665726f6d6d657420283231323729c034c00c000c000100001194000d0a73747561202837353229c00cc00c000c000100001194001411736f7665726f6d6d657420283231323729c00cc00c000c00010000119400070453747565c00c)
2020-11-23 19:40:41 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=0000000000010002000000000f5f636f6d70616e696f6e2d6c696e6b045f746370056c6f63616c00000c0001c00c000c000100001194001411736f7665726f6d6d657420283231323729c00cc00c000c000100001194000d0a73747561202837353229c00c)
2020-11-23 19:40:41 DEBUG: Sending multicast DNS request to 224.0.0.251:5353 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:41 DEBUG: Sending unicast DNS request to 10.0.150.25:5353 (Data=35ff01200000000000000000)
2020-11-23 19:40:41 DEBUG: Sending unicast DNS request to 10.0.150.250:5353 (Data=35ff012000020000000000000453747565085f616972706c6179045f746370056c6f63616c0000ff800111736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001)
2020-11-23 19:40:41 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:41 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:41 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000084000000000c0000000011736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c0000108001000011940109134d6f64656c4e616d653d4170706c65c2a0545610416c6c6f7750616972696e673d59455317426c7565746f6f7468416464726573733d5032378fa2281c6d6163416464726573733d35303a33323a33373a38663a61323a3239164e616d653d736f7665726f6d6d65742028323132372935556e697175654964656e7469666965723d45333135413732452d353645322d343341432d383833432d3041354236343735353635301853797374656d4275696c6456657273696f6e3d3...)
2020-11-23 19:40:42 DEBUG: Sending multicast DNS request to 224.0.0.251:5353 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:42 DEBUG: Sending unicast DNS request to 10.0.150.25:5353 (Data=35ff01200000000000000000)
2020-11-23 19:40:42 DEBUG: Sending unicast DNS request to 10.0.150.250:5353 (Data=35ff012000020000000000000453747565085f616972706c6179045f746370056c6f63616c0000ff800111736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001)
2020-11-23 19:40:42 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:42 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 19:40:42 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000084000000000c0000000011736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c0000108001000011940109134d6f64656c4e616d653d4170706c65c2a0545610416c6c6f7750616972696e673d59455317426c7565746f6f7468416464726573733d5032378fa2281c6d6163416464726573733d35303a33323a33373a38663a61323a3239164e616d653d736f7665726f6d6d65742028323132372935556e697175654964656e7469666965723d45333135413732452d353645322d343341432d383833432d3041354236343735353635301853797374656d4275696c6456657273696f6e3d3...)
Scan Results
========================================
```

10.0.150.25 is my Home Assistant docker. 
The result from 10.0.150.250 is from my Avahi-reflector. 1/20 times I find the Apple TV, but the rest of the times the scan results is blank.

**Comment by postlund** [comment] 2020-11-23 19:02
Ok, so you receive some kind of response from the reflector which I guess I don't handle correctly. Can you provide a complete dump of the message, so I can decode it and have a look? Currently lines are automatically cropped, but you can set a higher line limit like this:

    PYATV_BINARY_MAX_LINE=100000 atvremote scan --debug --mdns-debug

**Comment by wayller** [comment] 2020-11-23 19:33
> 
> 
> Ok, so you receive some kind of response from the reflector which I guess I don't handle correctly. Can you provide a complete dump of the message, so I can decode it and have a look? Currently lines are automatically cropped, but you can set a higher line limit like this:
> 
> ```
> PYATV_BINARY_MAX_LINE=100000 atvremote scan --debug --mdns-debug
> ```

Here you go:

´´´
/config # PYATV_BINARY_MAX_LINE=100000 atvremote scan --debug --mdns-debug
2020-11-23 20:33:11 DEBUG: Binding on *:5353
2020-11-23 20:33:11 DEBUG: Binding on 127.0.0.1:5353
2020-11-23 20:33:11 DEBUG: Binding on 10.0.150.25:5353
2020-11-23 20:33:11 DEBUG: Sending multicast DNS request to 224.0.0.251:5353 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:11 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:11 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:11 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000084000000000600000000085f616972706c6179045f746370056c6f63616c00000c00010000119400090654562d726f6dc00c0e5f6d6564696172656d6f74657476c015000c000100001194000d0a73747561202837353229c034c034000c000100001194001411736f7665726f6d6d657420283231323729c034c00c000c000100001194000d0a73747561202837353229c00cc00c000c000100001194001411736f7665726f6d6d657420283231323729c00cc00c000c00010000119400070453747565c00c)
2020-11-23 20:33:12 DEBUG: Sending multicast DNS request to 224.0.0.251:5353 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:12 DEBUG: Sending unicast DNS request to 10.0.150.25:5353 (Data=35ff01200000000000000000)
2020-11-23 20:33:12 DEBUG: Sending unicast DNS request to 10.0.150.250:5353 (Data=35ff012000020000000000000453747565085f616972706c6179045f746370056c6f63616c0000ff800111736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff8001)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000084000000000a0000000011736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c0000108001000011940109134d6f64656c4e616d653d4170706c65c2a0545610416c6c6f7750616972696e673d59455317426c7565746f6f7468416464726573733d5032378fa2281c6d6163416464726573733d35303a33323a33373a38663a61323a3239164e616d653d736f7665726f6d6d65742028323132372935556e697175654964656e7469666965723d45333135413732452d353645322d343341432d383833432d3041354236343735353635301853797374656d4275696c6456657273696f6e3d31384b3537484c6f63616c416972506c6179526563656976657250616972696e674964656e746974793d36384634413539332d413133372d343234462d383031362d3730413844433245324232370453747565085f616972706c6179c02d002f8001000011940009c02b00050000800040c14c0010800100001194015d0561636c3d301a64657669636569643d37383a32383a43413a44303a34453a36301b66656174757265733d307834343546384130302c30783143333430077273663d3078301166763d7032302e36312e312d383331373009666c6167733d3078340f6d6f64656c3d53594d464f4e49534b126d616e7566616374757265723d536f6e6f732073657269616c4e756d6265723d37382d32382d43412d44302d34452d36303a360d70726f746f766572733d312e310d737263766572733d3336362e302770693d62613061303561362d393135642d343663382d383764362d613262626466383863373430286769643d62613061303561362d393135642d343663382d383764362d613262626466383863373430066763676c3d3043706b3d36383662353831336261353861393530643230636562643134643164613034373263363236613166633830303931336433623437313638306631393139356534c00c002f8001000011940009c06900050000800040c01e000c000100001194000d0a73747561202837353229c01ec01e000c0001000011940002c00cc151000c000100001194000d0a73747561202837353229c151c151000c000100001194001411736f7665726f6d6d657420283231323729c151c151000c0001000011940002c14cc151000c00010000119400090654562d726f6dc151)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=0000840000000004000000000453747565085f616972706c6179045f746370056c6f63616c000021800100000078001b000000001b5812536f6e6f732d373832384341443034453630c01fc036002f8001000000780008c036000440000008c00c002f8001000000780009c00c00050000800040c036000180010000007800040a000068)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=00008400000000040000000011736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c000021800100000078001800000000c0010f736f7665726f6d6d65742d32303733c032c049002f8001000000780008c049000440000008c00c002f8001000000780009c00c00050000800040c049000180010000007800040a006416)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000000000001000200000000105f73706f746966792d636f6e6e656374045f746370056c6f63616c00000c0001c00c000c000100001194001411736f6e6f73373832384341443034453630c00cc00c000c000100001194001411736f6e6f73343841364238423043324331c00c)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000084000000000500000000105f73706f746966792d636f6e6e656374045f746370056c6f63616c00000c000100001194001411736f6e6f73373832384341443034453630c00c12536f6e6f732d373832384341443034453630c022002f8001000000780008c080000440000008c033002f8001000011940009c03300050000800040c03300218001000000780008000000000578c047c0330010800100001194001b0956455253494f4e3d311043506174683d2f73706f746966797a63)
2020-11-23 20:33:12 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=000084000000000600000000105f73706f746966792d636f6e6e656374045f746370056c6f63616c00000c000100001194001411736f6e6f73343841364238423043324331c00c12536f6e6f732d343841364238423043324331c022002f8001000000780008c080000440000008c033002f8001000011940009c03300050000800040c047000180010000007800040a000066c03300218001000000780008000000000578c047c0330010800100001194001b0956455253494f4e3d311043506174683d2f73706f746966797a63)
2020-11-23 20:33:13 DEBUG: Sending multicast DNS request to 224.0.0.251:5353 (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:13 DEBUG: Sending unicast DNS request to 10.0.150.25:5353 (Data=35ff01200000000000000000)
2020-11-23 20:33:13 DEBUG: Sending unicast DNS request to 10.0.150.250:5353 (Data=35ff0120000300000000000011736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476045f746370056c6f63616c0000ff80010453747565085f616972706c6179045f746370056c6f63616c0000ff80010654562d726f6d085f616972706c6179045f746370056c6f63616c0000ff8001)
2020-11-23 20:33:13 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:13 DEBUG: Received DNS response from ('10.0.150.25', 5353) (Data=35ff012000040000000000000b5f6170706c6574762d7632045f746370056c6f63616c00000c80010b5f746f7563682d61626c65045f746370056c6f63616c00000c80010e5f6d6564696172656d6f74657476045f746370056c6f63616c00000c8001085f616972706c6179045f746370056c6f63616c00000c8001)
2020-11-23 20:33:13 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=0000840000000010000000000654562d726f6d085f616972706c6179045f746370056c6f63616c00001080010000119401570561636c3d301a64657669636569643d34383a41363a42383a42303a43323a43311b66656174757265733d307834343546384130302c30783143333430077273663d3078301166763d7032302e36312e312d383331373009666c6167733d307834096d6f64656c3d417263126d616e7566616374757265723d536f6e6f732073657269616c4e756d6265723d34382d41362d42382d42302d43322d43313a470d70726f746f766572733d312e310d737263766572733d3336362e302770693d63663035316630312d353335382d343536652d623366612d303131363233653262373734286769643d63663035316630312d353335382d343536652d623366612d303131363233653262373734066763676c3d3043706b3d6530366237666437333862366161613465316365336165363437623362353566616434393566343261663539326265633039306238666663663534656563353611736f7665726f6d6d6574202832313237290e5f6d6564696172656d6f74657476c01c002f8001000000780009c00c00050000800040c1890021800100000078001800000000c0010f736f7665726f6d6d65742d32303733c021c189002f8001000011940009c06900050000800040c18900108001000011940109134d6f64656c4e616d653d4170706c65c2a0545610416c6c6f7750616972696e673d59455317426c7565746f6f7468416464726573733d5032378fa2281c6d6163416464726573733d35303a33323a33373a38663a61323a3239164e616d653d736f7665726f6d6d65742028323132372935556e697175654964656e7469666965723d45333135413732452d353645322d343341432d383833432d3041354236343735353635301853797374656d4275696c6456657273696f6e3d31384b3537484c6f63616c416972506c6179526563656976657250616972696e674964656e746974793d36384634413539332d413133372d343234462d383031362d3730413844433245324232370453747565c013002f8001000000780009c00c00050000800040c30d0021800100000078001b000000001b5812536f6e6f732d373832384341443034453630c021c30d002f8001000011940009c02b00050000800040c30d0010800100001194015d0561636c3d301a64657669636569643d37383a32383a43413a44303a34453a36301b66656174757265733d307834343546384130302c30783143333430077273663d3078301166763d7032302e36312e312d383331373009666c6167733d3078340f6d6f64656c3d53594d464f4e49534b126d616e7566616374757265723d536f6e6f732073657269616c4e756d6265723d37382d32382d43412d44302d34452d36303a360d70726f746f766572733d312e310d737263766572733d3336362e302770693d62613061303561362d393135642d343663382d383764362d613262626466383863373430286769643d62613061303561362d393135642d343663382d383764362d613262626466383863373430066763676c3d3043706b3d36383662353831336261353861393530643230636562643134643164613034373263363236613166633830303931336433623437313638306631393139356534c00c002f8001000011940009c02b00050000800040c19b000c000100001194000d0a73747561202837353229c19bc19b000c0001000011940002c189c013000c000100001194000d0a73747561202837353229c013c013000c000100001194001411736f7665726f6d6d657420283231323729c013c013000c0001000011940002c30dc013000c0001000011940002c00c)
2020-11-23 20:33:13 DEBUG: Received DNS response from ('10.0.150.250', 5353) (Data=0000840000000004000000000654562d726f6d085f616972706c6179045f746370056c6f63616c000021800100000078001b000000001b5812536f6e6f732d343841364238423043324331c021c038002f8001000000780008c038000440000008c00c002f8001000000780009c00c00050000800040c038000180010000007800040a000066)
2020-11-23 20:33:14 DEBUG: Auto-discovered TV-rom at 10.0.0.102:7000 (Protocol.AirPlay)
Scan Results
========================================
´´´

**Comment by postlund** [comment] 2020-11-26 10:42
Looks like records are spread over multiple responses, so a "complete" device is never seen. I will have to re-structure the code to collect all records first and parse services after that. Hopefully that should solve the problem. Not sure how much work that will be, but I will try to work on it as soon as I can.

**Comment by wayller** [comment] 2020-12-07 20:01
Tried your latest commit, looks better now. I find one out of two almost each time, the other one I find sometimes :)

**Comment by postlund** [comment] 2020-12-07 20:09
Are they all Apple TV 4(K)?

**Comment by wayller** [comment] 2020-12-07 20:11
> Are they all Apple TV 4(K)?

The one I find most of the time is ATV4, the other one is ATV4k.They are on two different VLANs, but that shouldn't matter.

**Comment by postlund** [comment] 2020-12-07 20:16
Ok, thanks! I have an Apple TV 3 for regression purposes on the network. For some reason it goes to deep sleep and wake with a short cycle (like every 40s or so). There's a gap from when the device has gone to sleep until the sleep proxy starts to respond for about ten seconds or so, making the device look unavailable when scanning. Perhaps that is what's happening here? It's easy to test, just continuously ping it and you should get ICMP redirects with IP the to sleep proxy it uses.

**Comment by wayller** [comment] 2020-12-08 20:03
> Ok, thanks! I have an Apple TV 3 for regression purposes on the network. For some reason it goes to deep sleep and wake with a short cycle (like every 40s or so). There's a gap from when the device has gone to sleep until the sleep proxy starts to respond for about ten seconds or so, making the device look unavailable when scanning. Perhaps that is what's happening here? It's easy to test, just continuously ping it and you should get ICMP redirects with IP the to sleep proxy it uses.

I will try that. 

Is it possible to update the HA integration to 0.7.5 or do I have to wait for the next release to HACS?

**Comment by paxswill** [comment] 2020-12-19 22:46
@wayller If you have the time, would you mind trying my branch in #899 to see if it helps with this?

**Comment by paxswill** [comment] 2020-12-29 20:56
I dug into this more, and it looks like it might (also) be an avahi bug. If you do a packet capture of what avahi is reflecting, they're not decompressing domain names in NSEC records before they cache them. This then leads to the original (compressed) data to be repeated by avahi, but the offset/pointer is wrong. I ran some of the above messages through Wireshark (just the ones from the reflector) and I'm seeing that the responses are cut off immediately after an NSEC record and Wireshark flags them as invalid. On my packet captures (full packets instead of being logged by pyatv) the data continues on while being interpreted as invalid NSEC tags.

This seems to be because of a mismatch in the mDNS RFC, which lists a bunch of extra records to use name compression on, while the NSEC RFC says specifically *not* to use name compression. I'll look into making a patch for avahi for this, but I'm not sure how active the maintainer is. (aside: this has been a fun rabbit hole to dive into).

**Comment by postlund** [comment] 2021-02-26 21:38
@wayller This problem is solved if I understand correctly? Maybe we can close the issue?

**Comment by wayller** [comment] 2021-03-02 18:57
> @wayller This problem is solved if I understand correctly? Maybe we can close the issue?

The device not found issue is fixed, but I can't see what my Apple TV plays.

**Closed** 2021-03-02 18:57 UTC
Labels: bug
