### ISSUE TITLE
Home Assistant integration does not work with tvOS 15

### ISSUE THREAD

**Issue by Eadger** [postlund/pyatv#1333] opened 2021-09-24 01:53 UTC
### Describe the bug

An aborted noted popped up every time when I try to add my Apple TV into hass.
![image](https://user-images.githubusercontent.com/45703375/134605545-653ac47b-5c6c-4cdb-98e0-0bdd58ee2f03.png)

### Error log

```log
<place log here>
```

### How to reproduce the bug?

After typed in the PIN code displayed on Apple TV.

### What is expected behavior?

Successfully add Apple TV Integration.

### Operating System

core-2021.9.7

### Python

Other

### pyatv

not sure

### Device

Apple TV 4K tvOS 15.0(19J346)

### Additional context

Using tvOS 15.0(19J346) on my Apple TV 4K.

**Comment by Smiggel** [comment] 2021-09-24 13:54
Same here. After entering the first pin (out of two - as it was before?) it stops working.

**Comment by postlund** [comment] 2021-09-24 17:19
It is because of tvOS 15, there are a couple of issues about it. You either have to sit tight and wait until I have updated the integration or run the beta version until I'm done.

https://github.com/postlund/hass-atv-beta

(It's available in HACS)

**Comment by Smiggel** [comment] 2021-09-25 13:32
> It is because of tvOS 15, there are a couple of issues about it. You either have to sit tight and wait until I have updated the integration or run the beta version until I'm done.
> 
> https://github.com/postlund/hass-atv-beta
> 
> (It's available in HACS)

Where do I have to look for? I can't seem to find the beta in HACS.

**Comment by DuncanRae** [comment] 2021-09-25 15:37
Hi,

I’ve installed the beta component and it sees all my Apple TV’s, and can interstate them with the pairing codes, although I do get the same error above, but HA still can’t see their state.  I have all my light automations set up to dim based on their playing, paused etc. state. Feels like I’m back in the 80s having to manually dim the lights. 

Apple TV state  in HA just says Off. I did remove he, from HA before installing the beta component, and they have been detected but the integration isn’t working yet. 

Thanks so much for your hard work on this. Really appreciate it and I really miss this function not working.

**Comment by postlund** [comment] 2021-09-25 16:09
@Smiggel it should be called "Apple TV beta component" or something like that. If it doesn't show up, try adding the address manually. That should work.

@DuncanRae Can you check the log? Might be that the connection fails for some reason.

**Comment by Smiggel** [comment] 2021-09-25 17:33
Installed the new beta and it works good for what I can see. HA sees my Apple TV. I was able to pair it and as soon as I play something on Netflix, I see it in HA! Nice. 

Can't say if it stable yet. Have to test it more. But looks really promising! Thanks!

**Comment by postlund** [comment] 2021-09-25 17:43
@Smiggel Sounds great! 👍 I'm very interested in stability related testing, so please report back on that!

**Comment by Smiggel** [comment] 2021-09-25 17:59
@postlund Will do. Will test it this week.

**Comment by DuncanRae** [comment] 2021-09-25 19:17
> @Smiggel it should be called "Apple TV beta component" or something like that. If it doesn't show up, try adding the address manually. That should work.
> 
> @DuncanRae Can you check the log? Might be that the connection fails for some reason.

Hi,

The only thing I can find of interest in the log is this which is happening over and over again. I do see it mentioned in another thread thee too:
2021-09-25 20:53:14 DEBUG (MainThread) [custom_components.apple_tv] Discovering device DEFB5818-ABD3-4C56-A2FB-21A5248ACC44
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.support.knock] Knocking at ports [3689, 7000, 49152, 32498] on 192.168.0.64
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.core.scan] Auto-discovered Lounge Apple TV at 192.168.0.64:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': 'D0:D2:B0:9C:A4:5A', 'deviceid': 'D0:D2:B0:9C:A4:5B', 'fex': '1d9/St5/FbwI', 'features': '0x4A7FDFD5,0xBC157FDE', 'flags': '0x644', 'gid': '0789667B-D142-4802-9308-F055822F7444', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV6,2', 'protovers': '1.1', 'pi': '16e57f49-27ed-4be3-a311-8cf2468ac8c4', 'psi': 'DD9F8738-B45B-475B-8901-34CD70478ADD', 'pk': '1d1aa49693908f1fcb1db0a14e0703296ba9ee180745e7c5d1210fbf6cf7b0a7', 'srcvers': '566.25.43', 'osvers': '15.0', 'vv': '2'})
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.core.scan] Auto-discovered D0D2B09CA45B@Lounge Apple TV at 192.168.0.64:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC157FDE', 'sf': '0x644', 'md': '0,1,2', 'am': 'AppleTV6,2', 'pk': '1d1aa49693908f1fcb1db0a14e0703296ba9ee180745e7c5d1210fbf6cf7b0a7', 'tp': 'UDP', 'vn': '65537', 'vs': '566.25.43', 'ov': '15.0', 'vv': '2'})
2021-09-25 20:53:14 DEBUG (MainThread) [custom_components.apple_tv] Failed to find device DEFB5818-ABD3-4C56-A2FB-21A5248ACC44 with address 192.168.0.64, trying to scan
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.support.net] Binding on *:5353
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.support.net] Binding on 127.0.0.1:0
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.support.net] Binding on 192.168.0.5:0
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.support.net] Binding on 172.30.32.1:0
2021-09-25 20:53:14 DEBUG (MainThread) [pyatv.support.net] Binding on 172.17.0.1:0

**Comment by postlund** [comment] 2021-09-25 20:28
@DuncanRae It's the same situation as in #1335. It has taken some time for me to grasp the situation, but I know exactly why this happens. Will try to work out a fix as soon as I can.

**Comment by DuncanRae** [comment] 2021-09-25 20:46
> @DuncanRae It's the same situation as in #1335. It has taken some time for me to grasp the situation, but I know exactly why this happens. Will try to work out a fix as soon as I can.

Awesome. Really appreciate the work!

**Comment by DAaviide** [comment] 2021-09-25 22:27
i cant find the beta in hacs

**Comment by Eadger** [comment] 2021-09-25 23:56
> It is because of tvOS 15, there are a couple of issues about it. You either have to sit tight and wait until I have updated the integration or run the beta version until I'm done.
> 
> https://github.com/postlund/hass-atv-beta
> 
> (It's available in HACS)

Cheers. Really appreciate.

**Comment by Smiggel** [comment] 2021-09-26 16:07
So far so good. Ran multiple test today with Netflix and Disney+ and it’s running fine. No problems so far.

**Comment by DAaviide** [comment] 2021-09-26 18:10
> > It is because of tvOS 15, there are a couple of issues about it. You either have to sit tight and wait until I have updated the integration or run the beta version until I'm done.
> > https://github.com/postlund/hass-atv-beta
> > (It's available in HACS)
> 
> Cheers. Really appreciate.
> 
> Couldn't find the "Apple TV beta component" or "pyatv" on HACS.
> How do I install manually?

same here😅
how can i do it

**Comment by postlund** [comment] 2021-09-26 19:42
Manually adding a repo can be done like this:

https://hacs.xyz/docs/faq/custom_repositories

Just use https://github.com/postlund/hass-atv-beta as address.

**Comment by Eadger** [comment] 2021-09-27 03:08
> Manually adding a repo can be done like this:
> 
> https://hacs.xyz/docs/faq/custom_repositories
> 
> Just use https://github.com/postlund/hass-atv-beta as address.

Got it. Cheers

**Comment by mpeterson** [comment] 2021-09-28 09:27
@postlund even with the config version bump that you pushed around 1 hour ago I'm still facing issues. I made sure to delete all references from `./storage/core.config_entries` too. 

My logs show:

```
Authentication problem

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 54, in start_pairing
    resp = await self.protocol.exchange_opack(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/protocol.py", line 80, in exchange_opack
    unpacked_object, _ = opack.unpack(payload)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 108, in unpack
    return _unpack(data, [])
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 115, in _unpack
    if data[0] == 0x01:
IndexError: index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 285, in async_pair_next_protocol
    await self.pairing.begin()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/pairing.py", line 53, in begin
    await error_handler(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: index out of range
```

This happens after the second input of an AirPlay pin. 

When I go to "Remote App and Devices" I have under devices "Unknown Device" entries as many times I tried to pair HASS to the AppleTV

**Comment by postlund** [comment] 2021-09-28 10:34
@mpeterson That looks like a bug or something I have not implemented in OPACK to me, cool! It would be great if you either enable debug logs for pyatv (https://github.com/postlund/hass-atv-beta#debug-logs) or try to reproduce with atvremote like this:

    atvremote --debug -s <ip to the device> --protocol companion pair

**Comment by filikun** [comment] 2021-09-28 13:14
It seems I have the same problem as above and got a log. @postlund I sent you a PM on discord!

**Comment by robyevolution** [comment] 2021-09-28 14:08
with the second beta version the player is always off, I tried to remove and reinstall the integration but it doesn't solve it

**Comment by postlund** [comment] 2021-09-28 14:49
> with the second beta version the player is always off, I tried to remove and reinstall the integration but it doesn't solve it

What does the log say?

**Comment by robyevolution** [comment] 2021-09-28 16:03
2021-09-28 18:02:31 WARNING (MainThread) [pyatv.protocols.airplay] Failed to set up remote control channel: not authenticated
2021-09-28 18:02:31 ERROR (MainThread) [custom_components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 261, in _connect_loop
    await self._connect(conf)
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 337, in _connect
    self.atv = await connect(conf, self.hass.loop, session=session)
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/__init__.py", line 96, in connect
    await atv.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/core/facade.py", line 425, in connect
    if await setup_data.connect():
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/__init__.py", line 879, in _connect
    await protocol.start()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/protocol.py", line 119, in start
    await self.connection.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/connection.py", line 100, in connect
    await self.loop.create_connection(lambda: self, self.host, self.port)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.110', 0)
2021-09-28 18:02:34 WARNING (MainThread) [pyatv.protocols.airplay] Failed to set up remote control channel: not authenticated
2021-09-28 18:02:34 ERROR (MainThread) [custom_components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 261, in _connect_loop
    await self._connect(conf)
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 337, in _connect
    self.atv = await connect(conf, self.hass.loop, session=session)
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/__init__.py", line 96, in connect
    await atv.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/core/facade.py", line 425, in connect
    if await setup_data.connect():
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/__init__.py", line 879, in _connect
    await protocol.start()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/protocol.py", line 119, in start
    await self.connection.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/connection.py", line 100, in connect
    await self.loop.create_connection(lambda: self, self.host, self.port)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.110', 0)

**Comment by postlund** [comment] 2021-09-28 16:33
@robyevolution Did AirPlay succeed to pair when you added the device?

**Comment by robyevolution** [comment] 2021-09-28 16:37
it is added correctly but the entity is always off, tried to restart home assistant and apple tv but the problem persists

**Comment by postlund** [comment] 2021-09-28 16:50
This line:

```
2021-09-28 18:02:31 WARNING (MainThread) [pyatv.protocols.airplay] Failed to set up remote control channel: not authenticated
```

Means that the MRP-over-AirPlay channel failed to set up, so there's basically nothing that provides metadata and that's why the device appears to be off. We need to figure out why that is happening. What device is this? Can you install pyatv so we can run atvremote? Or run it via docker?

**Comment by robyevolution** [comment] 2021-09-28 17:06
home assistant is installed on a proxmox container so I can update pyatv, with beta 1 it worked fine even if the MRP error came out.
i have a 4k tv apple

**Comment by postlund** [comment] 2021-09-28 17:25
Ok, that's interesting. Can you open `.storage/core.config_entries` and look for your device there, hopefully you find a `credentials` map containing the key "3" mapping to a long string (the AirPlay credentials), is that the case? The string should be four values in hex, concatenated by colons.

If the above is true, then you should verify the credentials with atvremote like this:

    atvremote -s <device ip> --airplay-credentials <value from above> --scan-protocol airplay playing

It should hopefully show what's playing. Instructions for docker is here:

https://pyatv.dev/documentation/#container-docker

You can use tag `v0.9.2` as that aligns with Home Assistant.

**Comment by robyevolution** [comment] 2021-09-28 17:34
give me this error:


2021-09-28 19:34:07 WARNING [pyatv.protocols.airplay]: Failed to set up remote control channel: not authenticated
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 716, in _run_application
    return await cli_handler(loop)
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 510, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 601, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/__init__.py", line 96, in connect
    await atv.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/core/facade.py", line 425, in connect
    if await setup_data.connect():
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/__init__.py", line 879, in _connect
    await protocol.start()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/protocol.py", line 119, in start
    await self.connection.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/pyatv/protocols/mrp/connection.py", line 100, in connect
    await self.loop.create_connection(lambda: self, self.host, self.port)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.110', 0)

**Comment by robyevolution** [comment] 2021-09-28 18:58
2021-09-28 20:55:53 ERROR (MainThread) [custom_components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 259, in _connect_loop
    conf = await self._scan()
  File "/home/homeassistant/.homeassistant/custom_components/apple_tv/__init__.py", line 290, in _scan
    identifiers = set(self.config_entry.data[CONF_IDENTIFIERS])
KeyError: 'identifiers'

**Comment by robyevolution** [comment] 2021-09-28 19:04
Now it works, the problem was that I had a static airplay password, removed the static password works fine.

**Comment by postlund** [comment] 2021-09-28 19:08
Ah, right, I should add a check for that (pyatv can detect if it is needed).

**Comment by mpeterson** [comment] 2021-09-29 05:33
@postlund I have the debug logs you requested. It has a lot of PII though, how can I give them to you without exposing it here?

**Comment by mpeterson** [comment] 2021-09-29 05:40
@postlund sent them via email to you

**Comment by postlund** [comment] 2021-09-29 05:58
> @postlund sent them via email to you

Perfect, thank you! Looks like the same issue as @filikun is seeing: some kind of NoOp is sent back. I'm looking into it.

**Comment by filikun** [comment] 2021-09-29 14:59
@mpeterson You seem to have the same problem as myself, do you happen to have the Apple TV on another VLAN than your Home Assistant?

**Comment by mpeterson** [comment] 2021-09-30 05:04
@filikun I actually do! How did you even think about that?

**Comment by filikun** [comment] 2021-09-30 05:07
> @filikun I actually do! How did you even think about that?

@postlund so this might be it. 

@mpeterson thing is I have this Xiaomi fan that just won’t work when on another vlan. But then the ATV did work before tvOS15 so I’m not sure what changed.

**Comment by postlund** [comment] 2021-09-30 05:34
@filikun Yes, it is most likely the case. It's a reasonable restriction, so I'm not that surprised. I'm re-working the message handling in Companion to support events, which will allow me to handle this case in a more elegant fashion. Would be great to have yet someone else confirm this, just to be sure.

**Comment by lafferlaffer** [comment] 2021-09-30 10:57
Hi @postlund
First of all, thank you so much for your work on this. It is much appreciated.

I installed the beta and it seems to be working great, so I just have a question;
How is the 'State' update handled when going from 'paused' to 'idle'? Have you made any changes in this version?
It seems to be changing to an 'idle' state much quicker now. Automations relying on the 'paused' state doesn't seem to work as (i) intended anymore.

Again; thank you 🤓

**Comment by postlund** [comment] 2021-09-30 17:38
@lafferlaffer It should be more or less the same I think. I have not made and significant changes to how state handling works, I merely update based on whatever the device sends to me.

Did you by any chance use `play_media` (or `play_url` if we are talking pyatv notion)? It will unfortunately break state on the device more or less completely, requiring a reboot to recover.

**Comment by lafferlaffer** [comment] 2021-09-30 18:21
@postlund ; just so there's no confusion, I'm using [hass-atv-beta](https://github.com/postlund/hass-atv-beta) because I upgraded to tvOS15.
The entity I'm looking at (and use for automation) is the _**media_player**_.

**Comment by postlund** [comment] 2021-09-30 19:52
@lafferlaffer That is correct!

**Comment by lafferlaffer** [comment] 2021-09-30 20:11
@postlund Ok, I just thought you'd like to know in case this is a bug in the beta.
The state of my Apple TV has been paused for a few hours now, even though we've been pausing and playing.

**Comment by postlund** [comment] 2021-09-30 20:14
@lafferlaffer It might be, please check the log. Hopefully there's something there.

**Comment by lafferlaffer** [comment] 2021-09-30 20:24
@postlund ; I found this if it's any use:

`
Logger: homeassistant
Source: custom_components/apple_tv/config_flow.py:111
Integration: Apple TV
First occurred: 17:54:33 (16 occurrences)
Last logged: 17:54:38
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 179, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/apple_tv/config_flow.py", line 177, in async_step_zeroconf
    return await self.async_find_device_wrapper(self.async_found_zeroconf_device)
  File "/config/custom_components/apple_tv/config_flow.py", line 203, in async_find_device_wrapper
    return await next_func()
  File "/config/custom_components/apple_tv/config_flow.py", line 181, in async_found_zeroconf_device
    await self.async_set_unique_id(self.device_identifier)
  File "/config/custom_components/apple_tv/config_flow.py", line 111, in device_identifier
    if self.atv.identifier in entry.data[CONF_IDENTIFIERS]:
KeyError: 'identifiers'
`

**Comment by dan003400** [comment] 2021-10-01 06:36
Updating to Beta fixed my MRP pairing failure 🙌🏻

**Comment by postlund** [comment] 2021-10-01 06:42
@lafferlaffer Yeah, that's the reason. I should not have left it in this state. You either have to revert to the previous version and remove the integrations before updating or manually remove them from `.storage/core.config_entries`. Hopefully this will not be a problem in future updates.

**Comment by RaZer0r** [comment] 2021-10-02 20:37
I also have my Atv 4K running on a seperate VLAN, and am unable to pair. If you need me to debug, give me a heads up :)

Currently debug is activated and I am running the beta from HACS.

Current error log:

Logger: custom_components.apple_tv.config_flow
Source: custom_components/apple_tv/config_flow.py:285 
Integration: apple_tv 
First occurred: 10:23:50 PM (1 occurrences) 
Last logged: 10:23:50 PM

Authentication problem
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 54, in start_pairing
    resp = await self.protocol.exchange_opack(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/protocol.py", line 80, in exchange_opack
    unpacked_object, _ = opack.unpack(payload)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 108, in unpack
    return _unpack(data, [])
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 115, in _unpack
    if data[0] == 0x01:
IndexError: index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 285, in async_pair_next_protocol
    await self.pairing.begin()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/pairing.py", line 53, in begin
    await error_handler(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: index out of range

If you need more info, let me know ;)

**Comment by postlund** [comment] 2021-10-02 20:39
@RaZer0r It would be great if you could move it so HA and the Apple TV is on the same VLAN. If that works, then we can pretty much assume that Companion won't work cross-VLAN..

**Comment by RaZer0r** [comment] 2021-10-02 21:24
> @RaZer0r It would be great if you could move it so HA and the Apple TV is on the same VLAN. If that works, then we can pretty much assume that Companion won't work cross-VLAN..

When both are on the same VLAN, it works

**Comment by bryshaw** [comment] 2021-10-07 16:36
I’m having issues. I installed using HACS. When I go to configure then add integration i am met with this:  “ERROR Config flow could not be loaded”

**Comment by postlund** [comment] 2021-10-07 21:18
@bryshaw Please check the log.

**Comment by postlund** [comment] 2021-10-08 20:09
You are missing a compiler so at least one of the dependencies to pyatv fails to compile.

**Comment by bryshaw** [comment] 2021-10-08 20:22
@postlund so I have to install a compiler? No idea what that means haha. Is it best if I just wait for it to come out of beta?

**Comment by postlund** [comment] 2021-10-14 05:55
@bryshaw A compiler (and some other libraries) are needed to compile some of the external dependencies pyatv has as they are written in C. Normally Home Assistant build binary versions of these called "wheels" for various platforms, so you don't need to care about that. The problem is that as the beta component is not shipped with Home Assistant yet, there's no pre-built versions of anything. If another integration depended on the same libraries, then it would have solved itself but that doesn't seem to be the case here. So I guess waiting for the uplift to get merged is the easiest way forward.

**Comment by BarryMar** [comment] 2021-10-14 14:52
I'm running HAOS 6.4 with core-2021.9.7 on RPi4.  I've never installed Apple TV integration before and have Apple TV 4K 2nd Gen (32 Gb) with TVOS 15 and no VLAN.  HomeKit is running on ATV and is happy.

I'm running into the same initial pairing problem as above with the default HAOS plugin, so I tried putting Beta 3 into the custom_components directory.  No change in behaviour and still can't pair.

Are there any TVOS settings that should not be used?
Any debug logs I can send that would be helpful?   (not totally sure where to set that/get them because there's nothing installed yet)

**Comment by Rrapa** [comment] 2021-10-21 16:39
Guys I'm constantly having that error on Apple 4K tvOS 15.1 (19J572)


Logger: custom_components.apple_tv.config_flow
Source: custom_components/apple_tv/config_flow.py:323 
Integration: Apple TV 
First occurred: 18:30:12 (2 occurrences) 
Last logged: 18:30:44

Authentication problem
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 54, in start_pairing
    resp = await self.protocol.exchange_opack(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/protocol.py", line 80, in exchange_opack
    unpacked_object, _ = opack.unpack(payload)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 126, in unpack
    return _unpack(data, [])
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/opack.py", line 133, in _unpack
    if data[0] == 0x01:
IndexError: index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 323, in async_pair_next_protocol
    await self.pairing.begin()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/companion/pairing.py", line 53, in begin
    await error_handler(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: index out of range

**Comment by Rrapa** [comment] 2021-10-21 17:25
> @Rrapa Which version of the integration are you running? Assuming it's not another OPACK type I'm missing, it should have been fixed in release 1.3 I think.

1.6 . .recently updated

**Comment by Rrapa** [comment] 2021-10-21 17:25
No issues on ATV 3 or Homepod mini

**Comment by Rrapa** [comment] 2021-10-21 17:26
Well .. I must say .. was struggling a bit with ATV3 mutliple restarts etc. .but finally pairing was successful

**Comment by emigrating** [comment] 2021-10-30 16:32
@postlund since you started requiring HAss 2021.11. 0 it's no longer possible to install ANY version using HACS which is a bit of an issue as I updated to 1.7.0 which didn't work out, so when I went to roll back to 1.6.0 it won't let me.

**Comment by Qonstrukt** [comment] 2021-11-04 17:49
I've been testing out the new version of the HA component and most of it works fine, but I'm having issues with the new power management features. In theory it's nice to have it mapped to HDMI CEC, but unfortunately for my cases it's kind of counterproductive:
I have a setup of a TV connected to an Onkyo receiver to which the ATV 4K is also connected. I use my ATV to play music, but I don't want my TV to turn on.
So what I did was disable "CEC Auto Power On" in my TV settings. But now I have the issue that my Onkyo receiver also no longer turns on when my ATV starts playing music. No problem though, I made an automation in HA to turn on the Onkyo as soon as the ATV starts playing something.
Unfortunately this no longer works, because the ATV is in standby state and won't switch out of it until the Onkyo receiver is turned on. But that's exactly the thing that I'm trying to do here. 😅 All the media info is still changing on the ATV device in HA, but the state just never leaves standby anymore.
Pressing the power button on the ATV in HA also doesn't turn on the Onkyo. Probably because it's honoring the request from the TV to ignore that. Even though it does let me turn it off using the ATV power button, haha.
Hope it's not too confusing!

**Comment by bverkron** [comment] 2021-11-28 04:32
> When I go to "Remote App and Devices" I have under devices "Unknown Device" entries as many times I tried to pair HASS to the AppleTV

@mpeterson did you find a solution for this? I have the same problem.

**Comment by postlund** [comment] 2021-12-06 10:02
> 

Sorry about the late response here, no excuses for that. So, here is my theory. The media player will report `standby` whenever pyatv reports that power state is `Off`. There is no "proper" off state in any of the known protocols so far, but we use a parameter called `logicalDeviceCount` which seems to correlate to the number of active output devices. Basically if HDMI is active, then it is 1 otherwise it is 0. Since the Apple TV can be used passively for audio streaming, like you do, this becomes a problem. It's obviously strange that the device can report power state "off" while still playing some media... So, one fix would be to change the power state to "on" whenever something is playing (or rather, when the device is not "idle"). One problem is that the power state will jump back and forth between on and off whenever plays or not. But that might be the best solution I guess, what do you think?

**Comment by postlund** [comment] 2021-12-06 10:04
@bverkron That looks good to me. I can't say why remotes are listed as "Unknown Device", but I have not looked into it either. Is this still the case with the latest version of the component?

**Closed** 2021-12-06 12:20 UTC
Labels: bug, 3rd party

**Comment by bverkron** [comment] 2021-12-06 19:50
> @bverkron That looks good to me. I can't say why remotes are listed as "Unknown Device", but I have not looked into it either. Is this still the case with the latest version of the component?

I see the latest version requires home assistant 2021.12 which apparently won't be out until Dec 11th. I will try the latest version of this component once I've upgraded to 2021.12 sometime in December, hopefully.

**Comment by bverkron** [comment] 2021-12-17 03:48
I updated and still had issues. It said said the following when I tried a few times.
![image](https://user-images.githubusercontent.com/19174503/146485611-8e246241-0b69-4707-9e75-a096537730d0.png)

I decided to reset / update the Apple TV itself (15.2 was available, I think it was on 15.1.x). While it was resetting / updating I noticed that the integration for that Apple TV had been "ignored" in the Integrations UI. Not sure how / when / why that happened but I stopped ignoring it and after that and the reset/update of the Apple TV I was able to pair it successfully. So not sure which of those several things fixed it, but it's working!

**Comment by postlund** [comment] 2021-12-17 06:47
That sounds very strange and I have no theories of how/why that happened I'm afraid. But good that it worked out in the end at least.

**Comment by CommittotheIndian** [comment] 2022-02-04 18:44
> I updated and still had issues. It said said the following when I tried a few times. ![image](https://user-images.githubusercontent.com/19174503/146485611-8e246241-0b69-4707-9e75-a096537730d0.png)
> 
> I decided to reset / update the Apple TV itself (15.2 was available, I think it was on 15.1.x). While it was resetting / updating I noticed that the integration for that Apple TV had been "ignored" in the Integrations UI. Not sure how / when / why that happened but I stopped ignoring it and after that and the reset/update of the Apple TV I was able to pair it successfully. So not sure which of those several things fixed it, but it's working!

I had the same image even after updating to 2022.2.0.

I looked and had my AppleTV ignored. Once I un-ignored it, it loaded right up no issues so I would go with that as the fix.

**Comment by palmerch1** [comment] 2022-04-17 13:07
Hello,

I am trying to connect my apple tv(tvOS 15.4.1) to HA(v2022.4.5).
I noticed that my version of tvOS wasn't supported by the 
"standard" Apple TV integration and discovered the beta version.
So, i installed Apple TV Beta(v3.0.1) via HACS(v1.24.5).
I can see the "Apple TV Beta" integration inside "HACS -> integrations",
but I guess it's not configurated properly as the apple tv is on another
network then my HA instance, but I didn't see any option to connect my apple tv.
My apple tv is in a 192.168.0.0/24 network, while the HA instance is in a 192.168.122.0/24 network.

Can someone please point me towards a config file or some other location where i can enter an ip address ?

I found a file which contains some properties but I don't know if this is the right file : /root/config/.storage/hacs/224041719.hacs

Thank you !

Best regards,
Christof.

**Comment by Qonstrukt** [comment] 2022-04-17 13:21
This is an outdated ticket. The integration in HA itself should be up to date with what is in HACS. 

Besides that, when you add an Apple TV manually in HA you can just specify an IP, so as long as inter network touring is set up properly it should technically work. I think you will also need mDNS forwarding/proxy'ing between those networks.
