### ISSUE TITLE
volume_set not working with tts.cloud_say

### ISSUE THREAD

**Issue by pug306d** [postlund/pyatv#1522] opened 2021-12-11 22:17 UTC
### Describe the bug

I am trying to set the volume level when using the tts.cloud_say service in home assistant.

I can see the volume is changed correctly as per the first action but then when the HomePod plays the tts it automatically changes the volume to what appears to be 0.2, after it finishes and playing it sets the volume back to what was set in the first action even though I do not specify a second volume set action.

It appears to be related to the fact the tts message is played using RAOP which has different volume controls but I cannot see how to set those so the tts messages are played at a volume they can be heard?

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Use these actions in a home assistant automation

action:
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    target:
      entity_id: media_player.living_room_homepod
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: tts.cloud_say
    data:
      entity_id: media_player.living_room_homepod
      message: Test Message

### What is expected behavior?

The tts message is played at the volume set in the automation.

### Operating System

HassOS

### Python

3.9

### pyatv

latest?

### Device

HomePod Mini

### Additional context

None

**Comment by postlund** [comment] 2021-12-12 11:32
Ah, this is a special little edge case I have missed. The only workaround right now is to set the volume after you started streaming, which I guess you can write an automaton for. But I will try to fix this before I release 0.9.8, which should happen some time this week.

**Comment by postlund** [comment] 2021-12-13 07:22
I thought I understood what was happening, but I can't seem to reproduce this myself. What OS version are you running on your HomePod? I have a theory of what could happen with some devices, but I cannot explain why it would revert back to the volume you set prior to using `cloud_say` *after* the streaming finished. There's no code for that. If you can easily reproduce, please enable logging and send the logs to me so I can analyze them further.

**Comment by pug306d** [comment] 2021-12-13 11:42
HomePod version is 15.1.1

When I first setup that automation I noticed the volume setting did not appear to apply when the tts was played on the HomePod so in the Home app on my iPhone I kept open the screen that lets me see what the HomePod is playing and its volume.  When the screen was open on my phone I run the automation and thats where I can see the volume is changed to the requested level, then tts is played with the lower volume and then the volume is changed back to the original value before the tts was played.

I have the HomePod and the HomePod mini and both are doing the same.

I did some more testing and it appears the tts is being played with a pre-configured volume for each device?  On my HomePod the tts is played at 0.7 always but on my HomePod Mini is is always played at 0.2.  I can set the volume either in the Home app or via media_player.volume_set and always the volume set is ignored when playing the tts.

I can change the volume whilst the tts is playing but when I play it again it plays at 0.7 for the HomePod or 0.2 on the Mini.

I found this on configuring logging but I'm not sure how to apply that on Home Assistant?

https://pyatv.dev/development/logging/

Thanks!

**Comment by postlund** [comment] 2021-12-13 13:21
I have tried reproduce exactly like you did, but I can't seem to do that. Looking a logs is probably the easiest way forward. You have instructions for enabling them here:

https://github.com/postlund/hass-atv-beta#debug-logs

**Comment by pug306d** [comment] 2021-12-13 17:09
I have the logs - there is a lot of information in them though which I don't want to share in a public forum, is there some specific entries I can share with you or some other way to share?

**Comment by postlund** [comment] 2021-12-13 17:15
Definitely! Send them by email, you have it in my profile page.

**Comment by postlund** [comment] 2021-12-15 06:44
Just wanted to check if you sent the logs or not (just so I didn't miss them)?

**Comment by 400HPMustang** [comment] 2021-12-15 15:46
I have a similar problem so I thought instead of another bug I would just piggy back here I have the following automation:

```
alias: Test Announcements
description: Test Announcements on the office HomePod
trigger:
  - platform: time
    at: '08:00:00'
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.office
  - service: tts.google_translate_say
    data:
      message: This is a test announcement
      entity_id: media_player.office
  - service: media_player.volume_set
    data:
      volume_level: 0.25
    target:
      entity_id: media_player.office
mode: single
```
I am seeing two different things happen:

1. When the media player is a single device (HomePod) the automation successfully sets the volume to 0.5 and makes the announcement. The trailing volume level call either is not occurring or is ignored but the volume stays at 0.5. 
2. When the media player is a group of devices (multiple HomePods) for some reason the volume sets to 0.25 before the announcement is made, then makes the announcement, and then the volume remains at 0.25

**Comment by pug306d** [comment] 2021-12-15 18:02
Logs shared today - sorry for delay :-)

**Comment by postlund** [comment] 2021-12-15 20:48
No worries! I'll have a look first thing in the morning!

**Comment by postlund** [comment] 2021-12-16 10:33
Ok, so I've had a look and I think I know what is going on. It was a bit tricky to reproduce at first until I realized what triggered this, but something like this work:

    $ atvremote -s <ip> set_volume=10 volume stream_file=sample.wav set_volume=30 volume stream_file=sample.wav

The first time `sameple.wav` is played, the volume will be 10%. The volume on the device then changes properly to 30% but is changed back to 10% as that is saved as an internal state.

To understand why this happens, you must know some details. It is possible (at least in AirPlay 2) for the receiver to report the "initial volume" when setting up a new stream. I use this as a base for volume in RAOP. The problem however is that there's no persistent connection in RAOP, it is only set up whenever something is about to be streamed. So in this scenario:

    $ atvremote -s <ip> set_volume=10 stream_file=sample.wav

The volume is stored as a local state inside RAOP *before* the stream starts and will override whatever "initial volume" says for all future to come. As long as volume has been set (internally) once, that volume will always be used by RAOP. This is perhaps not correct as the user might change volume on the receiver after streaming one time, which makes the initial volume and set volume differ. It is however how it works right now and the best I can do. It can only be improved if I decide to keep a persistent connection as I can subscribe to volume changes in that case. I'm not sure I want to take that route though.

Ok, so, the situation above is really just a problem when running RAOP standalone, i.e. with no other protocol. With the HomePod, we have the persistent MRP-over-AirPlay connection so we will always receive volume changes as push updates. So it's not a problem, except that the volume is stored inside MRP and not really accessible from RAOP right now. So what happens is this:

1. MRP sets volume to 10
2. MRP receives that volume has changed to 10
3. RAOP takes over control
4. No internal state for volume exists in RAOP, so it uses "initial volume" (10) and stores that internally
5. RAOP releases control after playback ends
6. MRP sets volume to 30
7. MRP receives that volume has changed to 30
8. RAOP takes over control
9. Now ROAP has an internal state (10) and uses that instead of initial volume (30)
10. RAOP releases control after playback ends

A somewhat simple way to fix this is to read out the volume (from MRP) before taking over controls in RAOP and correct the internal state. It's a bit tricky to do this properly and handle all the edge cases. There's however another way I'm leaning towards and that is via an internal state dispatcher I introduced when implementing #1500. It takes a bit more work, but it is the way I want it to work anyways as a preparation for more flexible listeners (#1301). It requires even more thought to get right, but allows me to implement push updates for volume changes in the end. That is currently not supported and something that can be noticed in Home Assistant.

**Comment by postlund** [comment] 2021-12-16 13:23
I believe I have solved this. Will try to update within the next few days or so.

**Comment by 400HPMustang** [comment] 2021-12-16 15:04
@postlund thank you for all of your work on this integration. It really is great and I appreciate how quickly you address issues.

**Comment by postlund** [comment] 2021-12-16 21:02
@400HPMustang Thanks for helping out and testing, appreciate it! 👍 It what's makes it possible.

This issue should be fixed by #1542, will be in next release.

**Comment by postlund** [comment] 2021-12-17 07:44
@400HPMustang Version 2.2.0 is out, please give it and try and let me know if it works better now!

**Comment by 400HPMustang** [comment] 2021-12-17 12:53
I just installed it and ran a test and I want to say it works but not quite. What I see happening is when the automation runs the volume jumps from whatever the current setting is to 0.5 and then to .25 and after it reaches 0.25 it plays the TTS. So it seems like it works but just out of order.

**Comment by postlund** [comment] 2021-12-17 12:56
Hmm, that's interesting. Can you take some new logs and send them to me? Would be great if you used the log points described [here](https://github.com/postlund/hass-atv-beta#debug-logs) to remove some noise. I assume it's the same automation (volume 0.9) now as well?

**Comment by 400HPMustang** [comment] 2021-12-17 13:10
@postlund In my case it's setting 0.5 then should play the TTS and then go back down to 0.25

This is what was logged after a few attempts:
```

2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 51639 (0.111746 vs 0.118716 => -0.006970)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 51640 (0.119728 vs 0.121046 => -0.001318)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 52149 (0.103764 vs 0.105828 => -0.002064)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 9438 (0.055873 vs 0.060149 => -0.004276)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 11745 (0.103764 vs 0.107598 => -0.003834)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 2210 (0.103764 vs 0.108145 => -0.004381)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 51642 (0.135692 vs 0.139529 => -0.003837)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 52151 (0.119728 vs 0.124067 => -0.004339)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 9440 (0.071837 vs 0.076531 => -0.004695)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 11747 (0.119728 vs 0.123999 => -0.004271)
2021-12-17 06:49:10 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 2212 (0.119728 vs 0.122638 => -0.002910)
2021-12-17 06:50:14 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 31021 (1.668209 vs 1.672010 => -0.003801)
2021-12-17 06:50:14 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 7222 (1.875737 vs 1.880342 => -0.004606)
2021-12-17 06:50:14 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 31215 (1.851791 vs 1.857076 => -0.005284)
2021-12-17 06:50:14 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 46764 (1.859773 vs 1.865521 => -0.005748)
2021-12-17 06:50:14 WARNING (MainThread) [pyatv.protocols.raop.raop] Too slow to keep up for seqno 57301 (1.732063 vs 1.737091 => -0.005028)
```

**Comment by postlund** [comment] 2021-12-17 13:12
@400HPMustang So the automation is to set 0.5, play TTS and then set 0.25 again? Those logs are unrelated, I need the traffic logs to say anything. You will likely not see those log points after the next release (unless your system is very stressed).

**Comment by 400HPMustang** [comment] 2021-12-17 13:24
Correct, the automation is to set 0.5, play TTS and then set 0.25 again. I think I forgot to reload my config.yaml file after I set logging. Is this what you're looking for?

```
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Sending periodic heartbeat 49 (AirPlay:10.107.112.181)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Sending RTSP/1.0 message: b'POST /feedback RTSP/1.0\r\nUser-Agent: AirPlay/540.31\r\nCSeq: 52\r\nDACP-ID: 9D9C8AD844089873\r\nActive-Remote: 3023947041\r\nClient-Instance: 9D9C8AD844089873\r\n\r\n'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Received: b'RTSP/1.0 200 OK\r\nDate: Fri, 17 Dec 2021 13:23:40 GMT\r\nContent-Length: 55\r\nContent-Type: application/x-apple-binary-plist\r\nServer: AirTunes/600.8.41\r\nCSeq: 52\r\n\r\nbplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Got RTSP response: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Fri, 17 Dec 2021 13:23:40 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/600.8.41', 'cseq': '52'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'):
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Got heartbeat 49 (AirPlay:10.107.112.181)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Sending periodic heartbeat 49 (AirPlay:10.107.112.68)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Sending RTSP/1.0 message: b'POST /feedback RTSP/1.0\r\nUser-Agent: AirPlay/540.31\r\nCSeq: 52\r\nDACP-ID: 54493AC2365943D4\r\nActive-Remote: 2592663211\r\nClient-Instance: 54493AC2365943D4\r\n\r\n'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Received: b'RTSP/1.0 200 OK\r\nDate: Fri, 17 Dec 2021 13:23:40 GMT\r\nContent-Length: 55\r\nContent-Type: application/x-apple-binary-plist\r\nServer: AirTunes/600.8.41\r\nCSeq: 52\r\n\r\nbplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Got RTSP response: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Fri, 17 Dec 2021 13:23:40 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/600.8.41', 'cseq': '52'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'):
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Got heartbeat 49 (AirPlay:10.107.112.68)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Sending periodic heartbeat 49 (AirPlay:10.107.112.134)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Sending RTSP/1.0 message: b'POST /feedback RTSP/1.0\r\nUser-Agent: AirPlay/540.31\r\nCSeq: 52\r\nDACP-ID: 192D0795FA46AA84\r\nActive-Remote: 2517121071\r\nClient-Instance: 192D0795FA46AA84\r\n\r\n'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Received: b'RTSP/1.0 200 OK\r\nDate: Fri, 17 Dec 2021 13:23:40 GMT\r\nContent-Length: 55\r\nContent-Type: application/x-apple-binary-plist\r\nServer: AirTunes/600.8.41\r\nCSeq: 52\r\n\r\nbplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Got RTSP response: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Fri, 17 Dec 2021 13:23:40 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/600.8.41', 'cseq': '52'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'):
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Got heartbeat 49 (AirPlay:10.107.112.134)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Sending periodic heartbeat 49 (AirPlay:10.107.112.198)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Sending RTSP/1.0 message: b'POST /feedback RTSP/1.0\r\nUser-Agent: AirPlay/540.31\r\nCSeq: 52\r\nDACP-ID: 67B041FE0E716217\r\nActive-Remote: 3094590941\r\nClient-Instance: 67B041FE0E716217\r\n\r\n'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Received: b'RTSP/1.0 200 OK\r\nDate: Fri, 17 Dec 2021 13:23:40 GMT\r\nContent-Length: 55\r\nContent-Type: application/x-apple-binary-plist\r\nServer: AirTunes/600.8.41\r\nCSeq: 52\r\n\r\nbplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Got RTSP response: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Fri, 17 Dec 2021 13:23:40 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/600.8.41', 'cseq': '52'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'):
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Got heartbeat 49 (AirPlay:10.107.112.198)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Sending periodic heartbeat 49 (AirPlay:10.107.112.156)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Sending RTSP/1.0 message: b'POST /feedback RTSP/1.0\r\nUser-Agent: AirPlay/540.31\r\nCSeq: 52\r\nDACP-ID: FAB7A615FAA190BE\r\nActive-Remote: 3608783269\r\nClient-Instance: FAB7A615FAA190BE\r\n\r\n'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Received: b'RTSP/1.0 200 OK\r\nDate: Fri, 17 Dec 2021 13:23:40 GMT\r\nContent-Length: 55\r\nContent-Type: application/x-apple-binary-plist\r\nServer: AirTunes/600.8.41\r\nCSeq: 52\r\n\r\nbplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Got RTSP response: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Fri, 17 Dec 2021 13:23:40 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/600.8.41', 'cseq': '52'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'):
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Got heartbeat 49 (AirPlay:10.107.112.156)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Sending periodic heartbeat 49 (AirPlay:10.107.112.142)
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Sending RTSP/1.0 message: b'POST /feedback RTSP/1.0\r\nUser-Agent: AirPlay/540.31\r\nCSeq: 52\r\nDACP-ID: DB9718A5D2A9DFB7\r\nActive-Remote: 1144956837\r\nClient-Instance: DB9718A5D2A9DFB7\r\n\r\n'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Received: b'RTSP/1.0 200 OK\r\nDate: Fri, 17 Dec 2021 13:23:40 GMT\r\nContent-Length: 55\r\nContent-Type: application/x-apple-binary-plist\r\nServer: AirTunes/600.8.41\r\nCSeq: 52\r\n\r\nbplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.support.http] Got RTSP response: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'date': 'Fri, 17 Dec 2021 13:23:40 GMT', 'content-length': '55', 'content-type': 'application/x-apple-binary-plist', 'server': 'AirTunes/600.8.41', 'cseq': '52'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14'):
2021-12-17 07:23:40 DEBUG (MainThread) [pyatv.core.protocol] Got heartbeat 49 (AirPlay:10.107.112.142)
2021-12-17 07:23:41 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/hassio_ingress/4Svoqz89gHNQvh-nQSBR9J0JyUFibT6HgGwqQlkzrlk/api/file to 10.107.112.141 (auth: False)
```

**Comment by postlund** [comment] 2021-12-21 07:40
Sorry about the delay! I need the complete log where I can see that volume levels being set (by the automation) as well as when pyatv starts streaming. Like previous time, it's probably the best if you send it by email to me.

**Comment by 400HPMustang** [comment] 2022-01-07 21:32
> Sorry about the delay! I need the complete log where I can see that volume levels being set (by the automation) as well as when pyatv starts streaming. Like previous time, it's probably the best if you send it by email to me.

Apologies from me as well. I've been out of the country for the last 14 days or so and just came back to this. Whatever was going on seems to have worked itself out because I don't seem to be having the issue anymore while trying to replicate it and get logs. So I think I'm good at the moment. I hope the person who opened this bug ticket got their issue worked out as well

**Comment by pug306d** [comment] 2022-01-07 22:44
I still have the original issue I reported, I emailed the logs for investigation. Thanks

**Comment by blacktirion** [comment] 2022-01-07 22:55
I too still have this issue. I've emailed some logs as well.

**Comment by si458** [comment] 2022-01-09 22:35
im also having a similar issue but mines very basic audio control with HA UI NO AUTOMATION
1. i start watching something on say Disney+
2. i can click 'Volume Up' and the volume turns up
3. BUT after a few seconds i get a notification in the web ui saying 'failed to call service media_play/volume_up' even through it turned it up?
4. ALSO when i click 'Volume Down', nothing happens? it doesnt turn it down and i get no error in the WebUI

**Comment by postlund** [comment] 2022-01-19 11:52
@si458 Internally pyatv will increase the volume and wait for the Apple TV to acknowledge the volume change, but it sounds like the acknowledgement doesn't come or is not handled properly. Can you enable and send me some logs when this happens?

I'll try to look at the remaining logs as soon as I can, pretty busy right now so I'm having a hard time keeping up to speed.

**Comment by si458** [comment] 2022-01-19 11:53
> @si458 Internally pyatv will increase the volume and wait for the Apple TV to acknowledge the volume change, but it sounds like the acknowledgement doesn't come or is not handled properly. Can you enable and send me some logs when this happens?
> 
> I'll try to look at the remaining logs as soon as I can, pretty busy right now so I'm having a hard time keeping up to speed.

sure will do when i get home tonight, how do i enable debug logs for you?

**Comment by postlund** [comment] 2022-01-19 11:59
> sure will do when i get home tonight, how do i enable debug logs for you?

Instructions are here:

https://github.com/postlund/hass-atv-beta#debug-logs

If you already have a default level, please set that to warning or higher as it pollutes the log and makes it unreadable otherwise. If you have more than one device set up via the Apple TV integration, I suggest you disable the other ones while extracting logs for the same reason.

**Comment by si458** [comment] 2022-01-19 12:18
@postlund ok i managed to do it remotely for you haha

logs are here - https://pastebin.com/raw/e98SPFbJ

rebooted my pi, then switch my TV on using my firestick in HA, then switched the firestick off, which then switched the tv to my apple tv input

then i tried a few commands
switch the apple tv on (it keeps showing as standby instead of idle?)
turned volume up (which from the logs show the command was successful but HA said it timed out?)
turned volume down (no logs shown i believe?)

i will do it properly when im home tonight for you and in front of the tv haha

**Comment by si458** [comment] 2022-01-20 08:59
@postlund sorry for the long delay,
here is the full logs for you - https://pastebin.com/raw/f7EFkNR1
i restarted my pi with my tv and apple tv both switched on,
waited a few mins, then pressed volume up a few times (which worked but HA kept saying the was an error?)
then pressed volume down a few times (never happened and HA also didnt show any errors?)
ive checked the logs myself and i believe it might be a HA issue because i can issue the remote.command of volume_down and it works a treat! but using the media player widget in HA doesnt seem to work?

**Comment by postlund** [comment] 2023-07-13 08:10
@400HPMustang Please retry with latest HA release, a lot has been improved with volume management. Hopefully it works now.

**Comment by si458** [comment] 2023-07-13 08:29
@postlund i confirm latest HA seens to of fixed the volume down issue i was having originally! thank you!

**Closed** 2023-07-13 08:31 UTC
Labels: bug, confirmation, raop
