### ISSUE TITLE
Unable to Pair Apple TV with tvOS15

### ISSUE THREAD

**Issue by rexterdigivalet** [postlund/pyatv#1458] opened 2021-11-09 09:11 UTC
### Describe the bug

I am unable to pair Apple TV with tvOS15
When i try to pair with MRP it shows the error like attached Below.
![Screenshot from 2021-11-09 14-36-48](https://user-images.githubusercontent.com/92011161/140895247-99cc2151-8f7a-43fe-b362-b555d8e9b4fb.png)
![Screenshot from 2021-11-09 14-37-27](https://user-images.githubusercontent.com/92011161/140895264-f80ee013-11f4-4aa3-880c-e1f7a8fb536a.png)

### Error log

```log
Traceback (most recent call last):
  File "/home/rexter/Desktop/Projects/AppleTV/.direnv/python-3.8.10/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/home/rexter/Desktop/Projects/AppleTV/.direnv/python-3.8.10/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 507, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
  File "/home/rexter/Desktop/Projects/AppleTV/.direnv/python-3.8.10/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/home/rexter/Desktop/Projects/AppleTV/.direnv/python-3.8.10/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 176, in pair
    pairing = await pair(conf, self.args.protocol, self.loop, **options)
  File "/home/rexter/Desktop/Projects/AppleTV/.direnv/python-3.8.10/lib/python3.8/site-packages/pyatv/__init__.py", line 119, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP

>>> An error occurred, full stack trace above
```

### How to reproduce the bug?

pip3 install pyatv
atvremote scan
atvremote --id DC:56:E7:59:79:46 --protocol mrp pair

### What is expected behavior?

Enter PIN on screen: 1234
Pairing seems to have succeeded, yey!
You may now use these credentials: 1650c36b816812561ee1a2ce55441c4d59aeee8287d3d0b90ad41e221c2ccc9b:eb6d47687f82327501d26e77bc3ee8b752034ad397c80cba37d91132717a1721:61383462633431372d383336362d346464632d386533622d333964356265303932663132:39376263616162332d356330652d343136362d623634302d326438656135616161636237

### Operating System

Linux

### Python

3.8

### pyatv

0.9.6

### Device

Apple TV tvOS15

### Additional context

Please help!

**Comment by postlund** [comment] 2021-11-09 09:36
You can only pair protocols actually supported by the device and MRP is not supported, which you can see in the list of protocols for the device (scan list). MRP was removed in tvOS 15 and what you are after is AirPlay. Preferably you pair all support protocols and provide credentials for them when calling atvremote.

**Comment by rexterdigivalet** [comment] 2021-11-09 09:55
So this means that I cannot control Apple TV with the command like Menu, Play, Left, Right, select, etc?

**Comment by postlund** [comment] 2021-11-09 10:07
Yes you can. But from tvOS 15, the MRP protocol is tunneled over AirPlay instead of being it's own protocol. So if you pair and set up AirPlay everything will work as intended.

**Comment by rexterdigivalet** [comment] 2021-11-09 10:17
![Screenshot from 2021-11-09 15-45-51](https://user-images.githubusercontent.com/92011161/140905879-8ac883f0-4cb1-43a6-ac24-232a3412380d.png)
But when i Try to move the selection (control like remote using command its fails)

**Comment by postlund** [comment] 2021-11-09 10:18
You need to include `--airplay-credentials <string you got from pairing>`.

**Comment by postlund** [comment] 2021-11-26 12:14
If you got it to work, please close this issue.

**Comment by postlund** [comment] 2021-12-06 09:34
Please re-open if you have further problems.

**Closed** 2021-12-06 09:34 UTC
Labels: bug
